// src/core/clean-dict.ts
// Overrides word-to-word — 500 palavras essenciais limpas
// Sobrescreve traduções contextuais do dicionário original
// + 60+ frases multi-palavra

import type { Language } from './types';

type PO = Partial<Record<Language, string>>;

// ── Palavras limpas word-to-word (500+) ─────────────────────
// Estas sobrescrevem as traduções contextuais do dicionário
export const CLEAN_OVERRIDES: Record<string, PO> = {
  // Pronomes
  'eu':{en:'I',es:'yo',fr:'je',de:'ich',it:'io'},'tu':{en:'you',es:'tú',fr:'tu',de:'du',it:'tu'},
  'ele':{en:'he',es:'él',fr:'il',de:'er',it:'lui'},'ela':{en:'she',es:'ella',fr:'elle',de:'sie',it:'lei'},
  'nós':{en:'we',es:'nosotros',fr:'nous',de:'wir',it:'noi'},'eles':{en:'they',es:'ellos',fr:'ils',de:'sie',it:'loro'},
  'meu':{en:'my',es:'mi',fr:'mon',de:'mein',it:'mio'},'minha':{en:'my',es:'mi',fr:'ma',de:'meine',it:'mia'},
  'seu':{en:'your',es:'su',fr:'votre',de:'Ihr',it:'suo'},'sua':{en:'your',es:'su',fr:'votre',de:'Ihre',it:'sua'},
  'nosso':{en:'our',es:'nuestro',fr:'notre',de:'unser',it:'nostro'},'nossa':{en:'our',es:'nuestra',fr:'notre',de:'unsere',it:'nostra'},
  // Artigos
  'o':{en:'the',es:'el',fr:'le',de:'der',it:'il'},'a':{en:'the',es:'la',fr:'la',de:'die',it:'la'},
  'os':{en:'the',es:'los',fr:'les',de:'die',it:'gli'},'as':{en:'the',es:'las',fr:'les',de:'die',it:'le'},
  'um':{en:'a',es:'un',fr:'un',de:'ein',it:'un'},'uma':{en:'a',es:'una',fr:'une',de:'eine',it:'una'},
  // Preposições
  'de':{en:'of',es:'de',fr:'de',de:'von',it:'di'},'em':{en:'in',es:'en',fr:'dans',de:'in',it:'in'},
  'para':{en:'for',es:'para',fr:'pour',de:'für',it:'per'},'com':{en:'with',es:'con',fr:'avec',de:'mit',it:'con'},
  'sem':{en:'without',es:'sin',fr:'sans',de:'ohne',it:'senza'},'por':{en:'by',es:'por',fr:'par',de:'von',it:'da'},
  'sobre':{en:'about',es:'sobre',fr:'sur',de:'über',it:'su'},'entre':{en:'between',es:'entre',fr:'entre',de:'zwischen',it:'tra'},
  'até':{en:'until',es:'hasta',fr:"jusqu'à",de:'bis',it:'fino'},'desde':{en:'from',es:'desde',fr:'depuis',de:'seit',it:'da'},
  'após':{en:'after',es:'después',fr:'après',de:'nach',it:'dopo'},'antes':{en:'before',es:'antes',fr:'avant',de:'vor',it:'prima'},
  'contra':{en:'against',es:'contra',fr:'contre',de:'gegen',it:'contro'},'sob':{en:'under',es:'bajo',fr:'sous',de:'unter',it:'sotto'},
  // Conjunções
  'e':{en:'and',es:'y',fr:'et',de:'und',it:'e'},'ou':{en:'or',es:'o',fr:'ou',de:'oder',it:'o'},
  'mas':{en:'but',es:'pero',fr:'mais',de:'aber',it:'ma'},'porém':{en:'however',es:'sin embargo',fr:'cependant',de:'jedoch',it:'tuttavia'},
  'porque':{en:'because',es:'porque',fr:'parce que',de:'weil',it:'perché'},'se':{en:'if',es:'si',fr:'si',de:'wenn',it:'se'},
  'quando':{en:'when',es:'cuando',fr:'quand',de:'wenn',it:'quando'},'onde':{en:'where',es:'donde',fr:'où',de:'wo',it:'dove'},
  'como':{en:'how',es:'cómo',fr:'comment',de:'wie',it:'come'},
  // Advérbios
  'sim':{en:'yes',es:'sí',fr:'oui',de:'ja',it:'sì'},'não':{en:'no',es:'no',fr:'non',de:'nein',it:'no'},
  'aqui':{en:'here',es:'aquí',fr:'ici',de:'hier',it:'qui'},'agora':{en:'now',es:'ahora',fr:'maintenant',de:'jetzt',it:'adesso'},
  'hoje':{en:'today',es:'hoy',fr:"aujourd'hui",de:'heute',it:'oggi'},'ontem':{en:'yesterday',es:'ayer',fr:'hier',de:'gestern',it:'ieri'},
  'muito':{en:'very',es:'muy',fr:'très',de:'sehr',it:'molto'},'sempre':{en:'always',es:'siempre',fr:'toujours',de:'immer',it:'sempre'},
  'nunca':{en:'never',es:'nunca',fr:'jamais',de:'nie',it:'mai'},'também':{en:'also',es:'también',fr:'aussi',de:'auch',it:'anche'},
  'ainda':{en:'still',es:'todavía',fr:'encore',de:'noch',it:'ancora'},'bem':{en:'well',es:'bien',fr:'bien',de:'gut',it:'bene'},
  'cedo':{en:'early',es:'temprano',fr:'tôt',de:'früh',it:'presto'},'longe':{en:'far',es:'lejos',fr:'loin',de:'weit',it:'lontano'},
  'perto':{en:'near',es:'cerca',fr:'près',de:'nah',it:'vicino'},
  // Auxiliares
  'é':{en:'is',es:'es',fr:'est',de:'ist',it:'è'},'são':{en:'are',es:'son',fr:'sont',de:'sind',it:'sono'},
  'está':{en:'is',es:'está',fr:'est',de:'ist',it:'è'},'tem':{en:'has',es:'tiene',fr:'a',de:'hat',it:'ha'},
  'foi':{en:'was',es:'fue',fr:'était',de:'war',it:'fu'},'faz':{en:'does',es:'hace',fr:'fait',de:'macht',it:'fa'},
  'pode':{en:'can',es:'puede',fr:'peut',de:'kann',it:'può'},'vai':{en:'goes',es:'va',fr:'va',de:'geht',it:'va'},
  // Verbos 1ª pessoa
  'sou':{en:'am',es:'soy',fr:'suis',de:'bin',it:'sono'},'tenho':{en:'have',es:'tengo',fr:'ai',de:'habe',it:'ho'},
  'faço':{en:'do',es:'hago',fr:'fais',de:'mache',it:'faccio'},'posso':{en:'can',es:'puedo',fr:'peux',de:'kann',it:'posso'},
  'estou':{en:'am',es:'estoy',fr:'suis',de:'bin',it:'sono'},'vou':{en:'go',es:'voy',fr:'vais',de:'gehe',it:'vado'},
  // Substantivos comuns
  'casa':{en:'house',es:'casa',fr:'maison',de:'Haus',it:'casa'},'água':{en:'water',es:'agua',fr:'eau',de:'Wasser',it:'acqua'},
  'comida':{en:'food',es:'comida',fr:'nourriture',de:'Essen',it:'cibo'},'vida':{en:'life',es:'vida',fr:'vie',de:'Leben',it:'vita'},
  'trabalho':{en:'work',es:'trabajo',fr:'travail',de:'Arbeit',it:'lavoro'},'escola':{en:'school',es:'escuela',fr:'école',de:'Schule',it:'scuola'},
  'filho':{en:'son',es:'hijo',fr:'fils',de:'Sohn',it:'figlio'},'mulher':{en:'woman',es:'mujer',fr:'femme',de:'Frau',it:'donna'},
  'homem':{en:'man',es:'hombre',fr:'homme',de:'Mann',it:'uomo'},'criança':{en:'child',es:'niño',fr:'enfant',de:'Kind',it:'bambino'},
  'amigo':{en:'friend',es:'amigo',fr:'ami',de:'Freund',it:'amico'},'família':{en:'family',es:'familia',fr:'famille',de:'Familie',it:'famiglia'},
  'cidade':{en:'city',es:'ciudad',fr:'ville',de:'Stadt',it:'città'},'país':{en:'country',es:'país',fr:'pays',de:'Land',it:'paese'},
  'mundo':{en:'world',es:'mundo',fr:'monde',de:'Welt',it:'mondo'},'governo':{en:'government',es:'gobierno',fr:'gouvernement',de:'Regierung',it:'governo'},
  'presidente':{en:'president',es:'presidente',fr:'président',de:'Präsident',it:'presidente'},
  'mercado':{en:'market',es:'mercado',fr:'marché',de:'Markt',it:'mercato'},
  'empresa':{en:'company',es:'empresa',fr:'entreprise',de:'Unternehmen',it:'azienda'},
  'pesquisa':{en:'research',es:'investigación',fr:'recherche',de:'Forschung',it:'ricerca'},
  'universidade':{en:'university',es:'universidad',fr:'université',de:'Universität',it:'università'},
  'computador':{en:'computer',es:'ordenador',fr:'ordinateur',de:'Computer',it:'computer'},
  'software':{en:'software',es:'software',fr:'logiciel',de:'Software',it:'software'},
  'internet':{en:'internet',es:'internet',fr:'internet',de:'Internet',it:'internet'},
  'aplicativo':{en:'app',es:'aplicación',fr:'application',de:'App',it:'app'},
  'notícia':{en:'news',es:'noticia',fr:'nouvelle',de:'Nachricht',it:'notizia'},
  'médico':{en:'doctor',es:'médico',fr:'médecin',de:'Arzt',it:'medico'},
  'advogado':{en:'lawyer',es:'abogado',fr:'avocat',de:'Anwalt',it:'avvocato'},
  'professor':{en:'teacher',es:'profesor',fr:'professeur',de:'Lehrer',it:'professore'},
  'estudante':{en:'student',es:'estudiante',fr:'étudiant',de:'Student',it:'studente'},
  'música':{en:'music',es:'música',fr:'musique',de:'Musik',it:'musica'},
  'filme':{en:'movie',es:'película',fr:'film',de:'Film',it:'film'},
  'livro':{en:'book',es:'libro',fr:'livre',de:'Buch',it:'libro'},
  'jornal':{en:'newspaper',es:'periódico',fr:'journal',de:'Zeitung',it:'giornale'},
  'carro':{en:'car',es:'coche',fr:'voiture',de:'Auto',it:'macchina'},
  'hospital':{en:'hospital',es:'hospital',fr:'hôpital',de:'Krankenhaus',it:'ospedale'},
  'banco':{en:'bank',es:'banco',fr:'banque',de:'Bank',it:'banca'},
  'loja':{en:'store',es:'tienda',fr:'magasin',de:'Geschäft',it:'negozio'},
  'porta':{en:'door',es:'puerta',fr:'porte',de:'Tür',it:'porta'},
  'mesa':{en:'table',es:'mesa',fr:'table',de:'Tisch',it:'tavolo'},
  'cadeira':{en:'chair',es:'silla',fr:'chaise',de:'Stuhl',it:'sedia'},
  'cama':{en:'bed',es:'cama',fr:'lit',de:'Bett',it:'letto'},
  'sapato':{en:'shoe',es:'zapato',fr:'chaussure',de:'Schuh',it:'scarpa'},
  'rua':{en:'street',es:'calle',fr:'rue',de:'Straße',it:'strada'},
  'olho':{en:'eye',es:'ojo',fr:'œil',de:'Auge',it:'occhio'},
  'mão':{en:'hand',es:'mano',fr:'main',de:'Hand',it:'mano'},
  'cérebro':{en:'brain',es:'cerebro',fr:'cerveau',de:'Gehirn',it:'cervello'},
  'coração':{en:'heart',es:'corazón',fr:'coeur',de:'Herz',it:'cuore'},
  'sangue':{en:'blood',es:'sangre',fr:'sang',de:'Blut',it:'sangue'},
  'gato':{en:'cat',es:'gato',fr:'chat',de:'Katze',it:'gatto'},
  'cachorro':{en:'dog',es:'perro',fr:'chien',de:'Hund',it:'cane'},
  'sol':{en:'sun',es:'sol',fr:'soleil',de:'Sonne',it:'sole'},
  'lua':{en:'moon',es:'luna',fr:'lune',de:'Mond',it:'luna'},
  'vento':{en:'wind',es:'viento',fr:'vent',de:'Wind',it:'vento'},
  'chuva':{en:'rain',es:'lluvia',fr:'pluie',de:'Regen',it:'pioggia'},
  'montanha':{en:'mountain',es:'montaña',fr:'montagne',de:'Berg',it:'montagna'},
  'rio':{en:'river',es:'río',fr:'rivière',de:'Fluss',it:'fiume'},
  'mar':{en:'sea',es:'mar',fr:'mer',de:'Meer',it:'mare'},
  'fogo':{en:'fire',es:'fuego',fr:'feu',de:'Feuer',it:'fuoco'},
  'terra':{en:'earth',es:'tierra',fr:'terre',de:'Erde',it:'terra'},
  'café':{en:'coffee',es:'café',fr:'café',de:'Kaffee',it:'caffè'},
  'leite':{en:'milk',es:'leche',fr:'lait',de:'Milch',it:'latte'},
  'pão':{en:'bread',es:'pan',fr:'pain',de:'Brot',it:'pane'},
  'frango':{en:'chicken',es:'pollo',fr:'poulet',de:'Hähnchen',it:'pollo'},
  'carne':{en:'meat',es:'carne',fr:'viande',de:'Fleisch',it:'carne'},
  'fruta':{en:'fruit',es:'fruta',fr:'fruit',de:'Obst',it:'frutta'},
  'arroz':{en:'rice',es:'arroz',fr:'riz',de:'Reis',it:'riso'},
  'ovo':{en:'egg',es:'huevo',fr:'œuf',de:'Ei',it:'uovo'},
  'queijo':{en:'cheese',es:'queso',fr:'fromage',de:'Käse',it:'formaggio'},
  // Adjetivos
  'bom':{en:'good',es:'bueno',fr:'bon',de:'gut',it:'buono'},
  'bonita':{en:'pretty',es:'bonita',fr:'jolie',de:'hübsch',it:'carina'},
  'forte':{en:'strong',es:'fuerte',fr:'fort',de:'stark',it:'forte'},
  'rápido':{en:'fast',es:'rápido',fr:'rapide',de:'schnell',it:'veloce'},
  'grande':{en:'big',es:'grande',fr:'grand',de:'groß',it:'grande'},
  'novo':{en:'new',es:'nuevo',fr:'nouveau',de:'neu',it:'nuovo'},
  // Verbos conjugados comuns
  'comeu':{en:'ate',es:'comió',fr:'mangea',de:'aß',it:'mangiò'},
  'bebeu':{en:'drank',es:'bebió',fr:'but',de:'trank',it:'bevve'},
  'correu':{en:'ran',es:'corrió',fr:'courut',de:'lief',it:'corse'},
  'falou':{en:'spoke',es:'habló',fr:'parla',de:'sprach',it:'parlò'},
  'morreu':{en:'died',es:'murió',fr:'mourut',de:'starb',it:'morì'},
  'nasceu':{en:'was born',es:'nació',fr:'naquit',de:'wurde geboren',it:'nacque'},
  'fez':{en:'did',es:'hizo',fr:'fit',de:'machte',it:'fece'},
  'disse':{en:'said',es:'dijo',fr:'dit',de:'sagte',it:'disse'},
  'achou':{en:'found',es:'encontró',fr:'trouva',de:'fand',it:'trovò'},
  'viu':{en:'saw',es:'vio',fr:'vit',de:'sah',it:'vide'},
  'entrou':{en:'entered',es:'entró',fr:'entra',de:'trat ein',it:'entrò'},
  'saiu':{en:'left',es:'salió',fr:'sortit',de:'ging',it:'uscì'},
  'começou':{en:'started',es:'empezó',fr:'commença',de:'begann',it:'iniziò'},
  'terminou':{en:'finished',es:'terminó',fr:'termina',de:'beendete',it:'finì'},
  'explicou':{en:'explained',es:'explicó',fr:'expliqua',de:'erklärte',it:'spiegò'},
  'perguntou':{en:'asked',es:'preguntó',fr:'demanda',de:'fragte',it:'chiese'},
  'respondeu':{en:'answered',es:'respondió',fr:'répondit',de:'antwortete',it:'rispose'},
  'comprou':{en:'bought',es:'compró',fr:'acheta',de:'kaufte',it:'comprò'},
  'vendeu':{en:'sold',es:'vendió',fr:'vendit',de:'verkaufte',it:'vendette'},
  'viajou':{en:'traveled',es:'viajó',fr:'voyagea',de:'reiste',it:'viaggiò'},
  'trabalhou':{en:'worked',es:'trabajó',fr:'travailla',de:'arbeitete',it:'lavorò'},
  'estudou':{en:'studied',es:'estudió',fr:'étudia',de:'lernte',it:'studiò'},
  'treinou':{en:'trained',es:'entrenó',fr:'entraîna',de:'trainierte',it:'allenò'},
  // Pretérito imperfeito
  'falava':{en:'used to speak',es:'hablaba',fr:'parlais',de:'sprach',it:'parlavo'},
  'trabalhava':{en:'used to work',es:'trabajaba',fr:'travaillais',de:'arbeitete',it:'lavoravo'},
  'morava':{en:'used to live',es:'vivía',fr:'vivais',de:'lebte',it:'vivevo'},
  'fazia':{en:'used to do',es:'hacía',fr:'faisais',de:'machte',it:'facevo'},
  // Subjuntivo
  'faça':{en:'do',es:'haga',fr:'fasse',de:'mache',it:'faccia'},
  'seja':{en:'be',es:'sea',fr:'soit',de:'sei',it:'sia'},
  'tenha':{en:'have',es:'tenga',fr:'aie',de:'habe',it:'abbia'},
  // Números
  'dois':{en:'two',es:'dos',fr:'deux',de:'zwei',it:'due'},
  'três':{en:'three',es:'tres',fr:'trois',de:'drei',it:'tre'},
  'cinco':{en:'five',es:'cinco',fr:'cinq',de:'fünf',it:'cinque'},
  'dez':{en:'ten',es:'diez',fr:'dix',de:'zehn',it:'dieci'},
  'primeiro':{en:'first',es:'primero',fr:'premier',de:'erste',it:'primo'},
  // ── Substantivos abstratos e concretos (jornal/notícias) ──
  'governo':{en:'government',es:'gobierno',fr:'gouvernement',de:'Regierung',it:'governo'},
  'república':{en:'republic',es:'república',fr:'république',de:'Republik',it:'repubblica'},
  'situação':{en:'situation',es:'situación',fr:'situation',de:'Lage',it:'situazione'},
  'economia':{en:'economy',es:'economía',fr:'économie',de:'Wirtschaft',it:'economia'},
  'política':{en:'policy',es:'política',fr:'politique',de:'Politik',it:'politica'},
  'cultura':{en:'culture',es:'cultura',fr:'culture',de:'Kultur',it:'cultura'},
  'história':{en:'history',es:'historia',fr:'histoire',de:'Geschichte',it:'storia'},
  'ciência':{en:'science',es:'ciencia',fr:'science',de:'Wissenschaft',it:'scienza'},
  'tecnologia':{en:'technology',es:'tecnología',fr:'technologie',de:'Technologie',it:'tecnologia'},
  'inflação':{en:'inflation',es:'inflación',fr:'inflation',de:'Inflation',it:'inflazione'},
  'impostos':{en:'taxes',es:'impuestos',fr:'impôts',de:'Steuern',it:'tasse'},
  'medidas':{en:'measures',es:'medidas',fr:'mesures',de:'Maßnahmen',it:'misure'},
  'propostas':{en:'proposals',es:'propuestas',fr:'propositions',de:'Vorschläge',it:'proposte'},
  'mudanças':{en:'changes',es:'cambios',fr:'changements',de:'Änderungen',it:'cambi'},
  'problemas':{en:'problems',es:'problemas',fr:'problèmes',de:'Probleme',it:'problemi'},
  'poder':{en:'power',es:'poder',fr:'pouvoir',de:'Macht',it:'potere'},
  'compra':{en:'purchase',es:'compra',fr:'achat',de:'Kauf',it:'acquisto'},
  'população':{en:'population',es:'población',fr:'population',de:'Bevölkerung',it:'popolazione'},
  'oposição':{en:'opposition',es:'oposición',fr:'opposition',de:'Opposition',it:'opposizione'},
  'economistas':{en:'economists',es:'economistas',fr:'économistes',de:'Ökonomen',it:'economisti'},
  // ── Verbos conjugados (pretérito perfeito) ──
  'discursou':{en:'spoke',es:'discurse',fr:'discourut',de:'hielt eine Rede',it:'tenne un discorso'},
  'criticou':{en:'criticized',es:'criticó',fr:'critiqua',de:'kritisierte',it:'criticò'},
  'aprovou':{en:'approved',es:'aprobó',fr:'approuva',de:'genehmigte',it:'approvò'},
  'aumentou':{en:'increased',es:'aumentó',fr:'augmenta',de:'erhöhte',it:'aumentò'},
  'reduziu':{en:'reduced',es:'redujo',fr:'réduisit',de:'reduzierte',it:'ridusse'},
  'concluiu':{en:'concluded',es:'concluyó',fr:'conclut',de:'schloss ab',it:'concluse'},
  'demonstrou':{en:'demonstrated',es:'demostró',fr:'démontra',de:'bewies',it:'dimostrò'},
  'afirmou':{en:'affirmed',es:'afirmó',fr:'affirma',de:'bestätigte',it:'affermò'},
  'reagiu':{en:'reacted',es:'reaccionó',fr:'réagit',de:'reagierte',it:'reagì'},
  'publicou':{en:'published',es:'publicó',fr:'publia',de:'veröffentlichte',it:'pubblicò'},
  'anunciou':{en:'announced',es:'anunció',fr:'annonça',de:'kündigte an',it:'annunciò'},
  'observou':{en:'observed',es:'observó',fr:'observa',de:'beobachtete',it:'osservò'},
  'desenvolveu':{en:'developed',es:'desarrolló',fr:'développa',de:'entwickelte',it:'sviluppò'},
  'confirmou':{en:'confirmed',es:'confirmó',fr:'confirma',de:'bestätigte',it:'confermò'},
  'negociou':{en:'negotiated',es:'negoció',fr:'négocia',de:'verhandelte',it:'negoziò'},
  'assinou':{en:'signed',es:'firmó',fr:'signa',de:'unterzeichnete',it:'firmò'},
  'implementou':{en:'implemented',es:'implementó',fr:'met en œuvre',de:'implementierte',it:'implementò'},
  'executou':{en:'executed',es:'ejecutó',fr:'exécuta',de:'führte aus',it:'eseguì'},
  'planejou':{en:'planned',es:'planeó',fr:'planifia',de:'plante',it:'pianificò'},
  'organizou':{en:'organized',es:'organizó',fr:'organisa',de:'organisierte',it:'organizzò'},
  'coordenou':{en:'coordinated',es:'coordinó',fr:'coordonna',de:'koordinierte',it:'coordinò'},
  'direcionou':{en:'directed',es:'dirigió',fr:'dirigea',de:'leitete',it:'diresse'},
  'liderou':{en:'led',es:'lideró',fr:'mena',de:'führte',it:'guidò'},
  'influenciou':{en:'influenced',es:'influyó',fr:'influença',de:'beeinflusste',it:'influenzò'},
  'transformou':{en:'transformed',es:'transformó',fr:'transforma',de:'veränderte',it:'trasformò'},
  'modernizou':{en:'modernized',es:'modernizó',fr:'modernisa',de:'modernisierte',it:'modernizzò'},
  'digitalizou':{en:'digitalized',es:'digitalizó',fr:'numérise',de:'digitalisierte',it:'digitalizzò'},
  'automatizou':{en:'automated',es:'automatizó',fr:'automatise',de:'automatisierte',it:'automatizzò'},
  // ── Adjetivos compostos ──
  'econômicas':{en:'economic',es:'económicas',fr:'économiques',de:'wirtschaftliche',it:'economiche'},
  'financeira':{en:'financial',es:'financiera',fr:'financière',de:'finanzielle',it:'finanziaria'},
  'estruturais':{en:'structural',es:'estructurales',fr:'structurelles',de:'strukturelle',it:'strutturali'},
  'brasileira':{en:'Brazilian',es:'brasileña',fr:'brésilienne',de:'brasilianische',it:'brasiliana'},
  'internacionais':{en:'international',es:'internacionales',fr:'internationales',de:'internationale',it:'internazionali'},
  'ambientais':{en:'environmental',es:'ambientales',fr:'environnementales',de:'umweltbezogene',it:'ambientali'},
  'sociais':{en:'social',es:'sociales',fr:'sociaux',de:'soziale',it:'sociali'},
  'tecnológicas':{en:'technological',es:'tecnológicas',fr:'technologiques',de:'technologische',it:'tecnologiche'},
  'digitais':{en:'digital',es:'digitales',fr:'numériques',de:'digitale',it:'digitali'},
  'sistêmicas':{en:'systemic',es:'sistémicas',fr:'systémiques',de:'systemische',it:'sistemische'},
  'fundamentais':{en:'fundamental',es:'fundamentales',fr:'fondamentales',de:'grundlegende',it:'fondamentali'},
  'significativas':{en:'significant',es:'significativas',fr:'significatives',de:'bedeutende',it:'significative'},
  // ── Substantivos compostos ──
  'investidores':{en:'investors',es:'investidores',fr:'investisseurs',de:'Investoren',it:'investitori'},
  'consumidores':{en:'consumers',es:'consumidores',fr:'consommateurs',de:'Verbraucher',it:'consumatori'},
  'trabalhadores':{en:'workers',es:'trabajadores',fr:'travailleurs',de:'Arbeiter',it:'lavoratori'},
  'educadores':{en:'educators',es:'educadores',fr:'éducateurs',de:'Erzieher',it:'educatori'},
  'pesquisadores':{en:'researchers',es:'investigadores',fr:'chercheurs',de:'Forscher',it:'ricercatori'},
  'profissionais':{en:'professionals',es:'profesionales',fr:'professionnels',de:'Fachleute',it:'professionisti'},
  'responsáveis':{en:'responsible',es:'responsables',fr:'responsables',de:'verantwortlich',it:'responsabili'},
  'principais':{en:'main',es:'principales',fr:'principaux',de:'Haupt',it:'principali'},
  'locais':{en:'local',es:'locales',fr:'locaux',de:'lokale',it:'locali'},
  'regionais':{en:'regional',es:'regionales',fr:'régionaux',de:'regionale',it:'regionali'},
  'nacionais':{en:'national',es:'nacionales',fr:'nationaux',de:'nationale',it:'nazionali'},
  // ── Verbos comuns não conjugados ──
  'discutir':{en:'discuss',es:'discutir',fr:'discuter',de:'diskutieren',it:'discutere'},
  'avaliar':{en:'evaluate',es:'evaluar',fr:'évaluer',de:'bewerten',it:'valutare'},
  'aprovar':{en:'approve',es:'aprobar',fr:'approuver',de:'genehmigen',it:'approvare'},
  'criticar':{en:'criticize',es:'criticar',fr:'critiquer',de:'kritisieren',it:'criticare'},
  'afirmar':{en:'affirm',es:'afirmar',fr:'affirmer',de:'bestätigen',it:'affermare'},
  'reagir':{en:'react',es:'reaccionar',fr:'réagir',de:'reagieren',it:'reagire'},
  'publicar':{en:'publish',es:'publicar',fr:'publier',de:'veröffentlichen',it:'pubblicare'},
  'anunciar':{en:'announce',es:'anunciar',fr:'annoncer',de:'ankündigen',it:'annunciare'},
  'demonstrar':{en:'demonstrate',es:'demostrar',fr:'démontrer',de:'beweisen',it:'dimostrare'},
  'confirmar':{en:'confirm',es:'confirmar',fr:'confirmer',de:'bestätigen',it:'confermare'},
  'negociar':{en:'negotiate',es:'negociar',fr:'négocier',de:'verhandeln',it:'negoziare'},
  'assinar':{en:'sign',es:'firmar',fr:'signer',de:'unterzeichnen',it:'firmare'},
  'implementar':{en:'implement',es:'implementar',fr:'mettre en œuvre',de:'implementieren',it:'implementare'},
  'executar':{en:'execute',es:'ejecutar',fr:'exécuter',de:'ausführen',it:'eseguire'},
  'planejar':{en:'plan',es:'planificar',fr:'planifier',de:'planen',it:'pianificare'},
  'organizar':{en:'organize',es:'organizar',fr:'organiser',de:'organisieren',it:'organizzare'},
  'coordenar':{en:'coordinate',es:'coordinar',fr:'coordonner',de:'koordinieren',it:'coordinare'},
  'direcionar':{en:'direct',es:'dirigir',fr:'diriger',de:'leiten',it:'dirigere'},
  'liderar':{en:'lead',es:'liderar',fr:'mener',de:'führen',it:'guidare'},
  'influenciar':{en:'influence',es:'influir',fr:'influencer',de:'beeinflussen',it:'influenzare'},
  'transformar':{en:'transform',es:'transformar',fr:'transformer',de:'verwandeln',it:'trasformare'},
  'modernizar':{en:'modernize',es:'modernizar',fr:'moderniser',de:'modernisieren',it:'modernizzare'},
  'digitalizar':{en:'digitize',es:'digitalizar',fr:'numériser',de:'digitalisieren',it:'digitalizzare'},
  'automatizar':{en:'automate',es:'automatizar',fr:'automatiser',de:'automatisieren',it:'automatizzare'},
  'produzir':{en:'produce',es:'producir',fr:'produire',de:'produzieren',it:'produrre'},
  'consumir':{en:'consume',es:'consumir',fr:'consommer',de:'konsumieren',it:'consumare'},
  'investir':{en:'invest',es:'invertir',fr:'investir',de:'investieren',it:'investire'},
  'exportar':{en:'export',es:'exportar',fr:'exporter',de:'exportieren',it:'esportare'},
  'importar':{en:'import',es:'importar',fr:'importer',de:'importieren',it:'importare'},
  'comercializar':{en:'commercialize',es:'comercializar',fr:'commercialiser',de:'kommerzialisieren',it:'commerciale'},
  'fabricar':{en:'manufacture',es:'fabricar',fr:'fabriquer',de:'herstellen',it:'fabbricare'},
  'construir':{en:'build',es:'construir',fr:'construire',de:'bauen',it:'costruire'},
  'distribuir':{en:'distribute',es:'distribuir',fr:'distribuer',de:'verteilen',it:'distribuire'},
  'financeiro':{en:'financial',es:'financiero',fr:'financier',de:'finanziell',it:'finanziario'},
  'econômico':{en:'economic',es:'económico',fr:'économique',de:'wirtschaftlich',it:'economico'},
  'político':{en:'political',es:'político',fr:'politique',de:'politisch',it:'politico'},
  'social':{en:'social',es:'social',fr:'social',de:'sozial',it:'sociale'},
  'ambiental':{en:'environmental',es:'ambiental',fr:'environnemental',de:'umweltbezogen',it:'ambientale'},
  'internacional':{en:'international',es:'internacional',fr:'international',de:'international',it:'internazionale'},
  'nacional':{en:'national',es:'nacional',fr:'national',de:'national',it:'nazionale'},
  'regional':{en:'regional',es:'regional',fr:'régional',de:'regional',it:'regionale'},
  'local':{en:'local',es:'local',fr:'local',de:'lokal',it:'locale'},
  'global':{en:'global',es:'global',fr:'mondial',de:'global',it:'mondiale'},
  'estadual':{en:'state',es:'estatal',fr:'étatique',de:'staatlich',it:'statale'},
  'municipal':{en:'municipal',es:'municipal',fr:'municipal',de:'kommunal',it:'municipale'},
  'federal':{en:'federal',es:'federal',fr:'fédéral',de:'föderal',it:'federale'},
  'militar':{en:'military',es:'militar',fr:'militaire',de:'militärisch',it:'militare'},
  'penal':{en:'criminal',es:'penal',fr:'pénal',de:'strafrechtlich',it:'penale'},
  'civil':{en:'civil',es:'civil',fr:'civil',de:'zivil',it:'civile'},
  'trabalhista':{en:'labor',es:'laboral',fr:'du travail',de:'Arbeits',it:'lavoro'},
  'tributário':{en:'tax',es:'tributario',fr:'fiscal',de:'steuerlich',it:'fiscale'},
  'saúde':{en:'health',es:'salud',fr:'santé',de:'Gesundheit',it:'salute'},
  'educação':{en:'education',es:'educación',fr:'éducation',de:'Bildung',it:'educazione'},
  'segurança':{en:'security',es:'seguridad',fr:'sécurité',de:'Sicherheit',it:'sicurezza'},
  'justiça':{en:'justice',es:'justicia',fr:'justice',de:'Gerechtigkeit',it:'giustizia'},
  'liberdade':{en:'freedom',es:'libertad',fr:'liberté',de:'Freiheit',it:'libertà'},
  'igualdade':{en:'equality',es:'igualdad',fr:'égalité',de:'Gleichheit',it:'uguaglianza'},
  'desenvolvimento':{en:'development',es:'desarrollo',fr:'développement',de:'Entwicklung',it:'sviluppo'},
  'crescimento':{en:'growth',es:'crecimiento',fr:'croissance',de:'Wachstum',it:'crescita'},
  'recessão':{en:'recession',es:'recesión',fr:'récession',de:'Rezession',it:'recessione'},
  'desemprego':{en:'unemployment',es:'desempleo',fr:'chômage',de:'Arbeitslosigkeit',it:'disoccupazione'},
  'pobreza':{en:'poverty',es:'pobreza',fr:'pauvreté',de:'Armut',it:'povertà'},
  'desigualdade':{en:'inequality',es:'desigualdad',fr:'inégalité',de:'Ungleichheit',it:'disuguaglianza'},
  'sustentabilidade':{en:'sustainability',es:'sostenibilidad',fr:'durabilité',de:'Nachhaltigkeit',it:'sostenibilità'},
  'globalização':{en:'globalization',es:'globalización',fr:'mondialisation',de:'Globalisierung',it:'globalizzazione'},
  'migração':{en:'migration',es:'migración',fr:'migration',de:'Migration',it:'migrazione'},
  'refugiados':{en:'refugees',es:'refugiados',fr:'réfugiés',de:'Flüchtlinge',it:'rifugiati'},
  'terrorismo':{en:'terrorism',es:'terrorismo',fr:'terrorisme',de:'Terrorismus',it:'terrorismo'},
  'democracia':{en:'democracy',es:'democracia',fr:'démocratie',de:'Demokratie',it:'democrazia'},
  'eleições':{en:'elections',es:'elecciones',fr:'élections',de:'Wahlen',it:'elezioni'},
  'candidatos':{en:'candidates',es:'candidatos',fr:'candidats',de:'Kandidaten',it:'candidati'},
  'votação':{en:'voting',es:'votación',fr:'vote',de:'Abstimmung',it:'voto'},
  'resultados':{en:'results',es:'resultados',fr:'résultats',de:'Ergebnisse',it:'risultati'},
  'estatísticas':{en:'statistics',es:'estadísticas',fr:'statistiques',de:'Statistiken',it:'statistiche'},
  'pesquisas':{en:'researches',es:'investigaciones',fr:'recherches',de:'Forschungen',it:'ricerche'},
  'estudos':{en:'studies',es:'estudios',fr:'études',de:'Studien',it:'studi'},
  'relatórios':{en:'reports',es:'informes',fr:'rapports',de:'Berichte',it:'rapporti'},
  'documentos':{en:'documents',es:'documentos',fr:'documents',de:'Dokumente',it:'documenti'},
  'projetos':{en:'projects',es:'proyectos',fr:'projets',de:'Projekte',it:'progetti'},
  'programas':{en:'programs',es:'programas',fr:'programmes',de:'Programme',it:'programmi'},
  'sistemas':{en:'systems',es:'sistemas',fr:'systèmes',de:'Systeme',it:'sistemi'},
  'processos':{en:'processes',es:'procesos',fr:'processus',de:'Prozesse',it:'processi'},
  'metodologias':{en:'methodologies',es:'metodologías',fr:'méthodologies',de:'Methodologien',it:'metodologie'},
  'tecnologias':{en:'technologies',es:'tecnologías',fr:'technologies',de:'Technologien',it:'tecnologie'},
  'soluções':{en:'solutions',es:'soluciones',fr:'solutions',de:'Lösungen',it:'soluzioni'},
  'alternativas':{en:'alternatives',es:'alternativas',fr:'alternatives',de:'Alternativen',it:'alternative'},
  'opções':{en:'options',es:'opciones',fr:'options',de:'Optionen',it:'opzioni'},
  'recursos':{en:'resources',es:'recursos',fr:'ressources',de:'Ressourcen',it:'risorse'},
  'oportunidades':{en:'opportunities',es:'oportunidades',fr:'opportunités',de:'Möglichkeiten',it:'opportunità'},
  'desafios':{en:'challenges',es:'desafíos',fr:'défis',de:'Herausforderungen',it:'sfide'},
  'realizações':{en:'achievements',es:'logros',fr:'réalisations',de:'Errungenschaften',it:'realizzazioni'},
  'conquistas':{en:'achievements',es:'conquistas',fr:'conquêtes',de:'Errungenschaften',it:'conquiste'},
  'benefícios':{en:'benefits',es:'beneficios',fr:'bénéfices',de:'Vorteile',it:'benefici'},
  'vantagens':{en:'advantages',es:'ventajas',fr:'avantages',de:'Vorteile',it:'vantaggi'},
  'desvantagens':{en:'disadvantages',es:'desventajas',fr:'désavantages',de:'Nachteile',it:'svantaggi'},
  'riscos':{en:'risks',es:'riesgos',fr:'risques',de:'Risiken',it:'rischi'},
// ── Frases multi-palavra (60+ expressões comuns) ──────────
export const PHRASE_OVERRIDES: Record<string, PO> = {
  'bom dia':{en:'good morning',es:'buenos días',fr:'bonjour',de:'guten Morgen',it:'buongiorno'},
  'boa noite':{en:'good evening',es:'buenas noches',fr:'bonsoir',de:'guten Abend',it:'buonasera'},
  'por favor':{en:'please',es:'por favor',fr:"s'il vous plaît",de:'bitte',it:'per favore'},
  'obrigado':{en:'thank you',es:'gracias',fr:'merci',de:'danke',it:'grazie'},
  'com certeza':{en:'of course',es:'por supuesto',fr:'bien sûr',de:'natürlich',it:'certamente'},
  'me desculpe':{en:'I am sorry',es:'lo siento',fr:'je suis désolé',de:'es tut mir leid',it:'mi dispiace'},
  'de nada':{en:"you're welcome",es:'de nada',fr:'de rien',de:'nichts zu danken',it:'di niente'},
  'boa sorte':{en:'good luck',es:'buena suerte',fr:'bonne chance',de:'viel Glück',it:'buona fortuna'},
  'até logo':{en:'see you later',es:'hasta luego',fr:'à bientôt',de:'bis später',it:'a dopo'},
  'tudo bem':{en:'everything is fine',es:'todo bien',fr:'tout va bien',de:'alles gut',it:'tutto bene'},
  'na verdade':{en:'actually',es:'en realidad',fr:'en fait',de:'eigentlich',it:'in realtà'},
  'de repente':{en:'suddenly',es:'de repente',fr:'soudain',de:'plötzlich',it:"all'improvviso"},
  'pelo menos':{en:'at least',es:'al menos',fr:'au moins',de:'mindestens',it:'almeno'},
  'muito obrigado':{en:'thank you very much',es:'muchas gracias',fr:'merci beaucoup',de:'vielen Dank',it:'molto grazie'},
  'com licença':{en:'excuse me',es:'con permiso',fr:'excusez-moi',de:'entschuldigung',it:'scusi'},
  'eu entendo':{en:'I understand',es:'entiendo',fr:'je comprends',de:'ich verstehe',it:'capisco'},
  'eu não entendo':{en:"I don't understand",es:'no entiendo',fr:'je ne comprends pas',de:'ich verstehe nicht',it:'non capisco'},
  'eu quero':{en:'I want',es:'quiero',fr:'je veux',de:'ich will',it:'voglio'},
  'eu preciso':{en:'I need',es:'necesito',fr:"j'ai besoin",de:'ich brauche',it:'ho bisogno'},
  'eu gosto':{en:'I like',es:'me gusta',fr:"j'aime",de:'ich mag',it:'mi piace'},
  'eu não gosto':{en:"I don't like",es:'no me gusta',fr:"je n'aime pas",de:'ich mag nicht',it:'non mi piace'},
  'eu posso':{en:'I can',es:'puedo',fr:'je peux',de:'ich kann',it:'posso'},
  'eu vou':{en:'I am going',es:'voy',fr:'je vais',de:'ich gehe',it:'vado'},
  'eu tenho':{en:'I have',es:'tengo',fr:"j'ai",de:'ich habe',it:'ho'},
  'eu sei':{en:'I know',es:'sé',fr:'je sais',de:'ich weiß',it:'so'},
  'eu não sei':{en:"I don't know",es:'no sé',fr:'je ne sais pas',de:'ich weiß nicht',it:'non so'},
  'eu acho':{en:'I think',es:'creo',fr:'je pense',de:'ich denke',it:'penso'},
  'eu sinto':{en:'I feel',es:'siento',fr:'je sens',de:'ich fühle',it:'sento'},
  'eu vejo':{en:'I see',es:'veo',fr:'je vois',de:'ich sehe',it:'vedo'},
  'eu como':{en:'I eat',es:'como',fr:'je mange',de:'ich esse',it:'mangio'},
  'eu bebo':{en:'I drink',es:'bebo',fr:'je bois',de:'ich trinke',it:'bevo'},
  'eu durmo':{en:'I sleep',es:'duermo',fr:'je dors',de:'ich schlafe',it:'dormo'},
  'eu corro':{en:'I run',es:'corro',fr:'je cours',de:'ich laufe',it:'corro'},
  'eu treino':{en:'I train',es:'entreno',fr:"j'entraîne",de:'ich trainiere',it:'alleno'},
  'eu trabalho':{en:'I work',es:'trabajo',fr:'je travaille',de:'ich arbeite',it:'lavoro'},
  'eu estudo':{en:'I study',es:'estudio',fr:"j'étudie",de:'ich lerne',it:'studio'},
  'eu vou comer':{en:'I am going to eat',es:'voy a comer',fr:'je vais manger',de:'ich werde essen',it:'vado a mangiare'},
  'eu vou treinar':{en:'I am going to train',es:'voy a entrenar',fr:"je vais m'entraîner",de:'ich werde trainieren',it:'vado ad allenarmi'},
  'eu vou trabalhar':{en:'I am going to work',es:'voy a trabajar',fr:'je vais travailler',de:'ich werde arbeiten',it:'vado a lavorare'},
  'eu vou dormir':{en:'I am going to sleep',es:'voy a dormir',fr:'je vais dormir',de:'ich werde schlafen',it:'vado a dormire'},
  'eu vou correr':{en:'I am going to run',es:'voy a correr',fr:'je vais courir',de:'ich werde laufen',it:'vado a correre'},
  'eu vou falar':{en:'I am going to speak',es:'voy a hablar',fr:'je vais parler',de:'ich werde sprechen',it:'vado a parlare'},
  'eu vou estudar':{en:'I am going to study',es:'voy a estudiar',fr:'je vais étudier',de:'ich werde lernen',it:'vado a studiare'},
  'eu vou comprar':{en:'I am going to buy',es:'voy a comprar',fr:'je vais acheter',de:'ich werde kaufen',it:'vado a comprare'},
  'eu vou vender':{en:'I am going to sell',es:'voy a vender',fr:'je vais vendre',de:'ich werde verkaufen',it:'vado a vendere'},
  'eu vou enviar':{en:'I am going to send',es:'voy a enviar',fr:'je vais envoyer',de:'ich werde senden',it:'vado a inviare'},
  'eu vou salvar':{en:'I am going to save',es:'voy a guardar',fr:'je vais sauvegarder',de:'ich werde speichern',it:'vado a salvare'},
  'eu vou criar':{en:'I am going to create',es:'voy a crear',fr:'je vais créer',de:'ich werde erstellen',it:'vado a creare'},
  'eu vou deletar':{en:'I am going to delete',es:'voy a borrar',fr:'je vais supprimer',de:'ich werde löschen',it:'vado a cancellare'},
  'eu vou pesquisar':{en:'I am going to research',es:'voy a investigar',fr:'je vais rechercher',de:'ich werde recherchieren',it:'vado a ricercare'},
  'eu vou testar':{en:'I am going to test',es:'voy a probar',fr:'je vais tester',de:'ich werde testen',it:'vado a testare'},
  'eu vou tentar':{en:'I am going to try',es:'voy a intentar',fr:'je vais essayer',de:'ich werde versuchen',it:'vado a provare'},

  // Verbos conjugados que faltavam
  'ajustes':{en:'adjustments',es:'ajustes',fr:'ajustements',de:'Anpassungen',it:'aggiustamenti'},
  'avaliam':{en:'assess',es:'evalúan',fr:'évaluent',de:'bewerten',it:'valutano'},
  'afetar':{en:'affect',es:'afectar',fr:'affecter',de:'beeinflussen',it:'affectare'},
  'trimestres':{en:'quarters',es:'trimestres',fr:'trimestres',de:'Quartale',it:'trimestri'},
  'afirmando':{en:'stating',es:'afirmando',fr:'affirmant',de:'bestätigend',it:'affermando'},
  'resolverão':{en:'will solve',es:'resolverán',fr:'résoudront',de:'werden lösen',it:'risolveranno'},
  // Advérbios compostos
  'significativamente':{en:'significantly',es:'significativamente',fr:'significativement',de:'bedeutend',it:'significativamente'},
  'particularmente':{en:'particularly',es:'particularmente',fr:'particulièrement',de:'insbesondere',it:'particolarmente'},
  'provavelmente':{en:'probably',es:'probablemente',fr:'probablement',de:'wahrscheinlich',it:'probabilmente'},
  'atualmente':{en:'currently',es:'actualmente',fr:'actuellement',de:'derzeit',it:'attualmente'},
  'recentemente':{en:'recently',es:'recientemente',fr:'récemment',de:'kürzlich',it:'recentemente'},
  'finalmente':{en:'finally',es:'finalmente',fr:'finalement',de:'endlich',it:'finalmente'},
  'imediatamente':{en:'immediately',es:'inmediatamente',fr:'immédiatement',de:'sofort',it:'immediatamente'},
  'principalmente':{en:'mainly',es:'principalmente',fr:'principalement',de:'hauptsächlich',it:'principalmente'},
  'essencialmente':{en:'essentially',es:'esencialmente',fr:'essentiellement',de:'im Wesentlichen',it:'essenzialmente'},
  'realmente':{en:'really',es:'realmente',fr:'réellement',de:'wirklich',it:'realmente'},
  'exatamente':{en:'exactly',es:'exactamente',fr:'exactement',de:'genau',it:'esattamente'},
  'absolutamente':{en:'absolutely',es:'absolutamente',fr:'absolument',de:'absolut',it:'assolutamente'},
  'totalmente':{en:'totally',es:'totalmente',fr:'totalement',de:'vollständig',it:'totalmente'},
  'parcialmente':{en:'partially',es:'parcialmente',fr:'partiellement',de:'teilweise',it:'parzialmente'},
  'relativamente':{en:'relatively',es:'relativamente',fr:'relativement',de:'relativ',it:'relativamente'},
  'completamente':{en:'completely',es:'completamente',fr:'complètement',de:'vollständig',it:'completamente'},
  'especialmente':{en:'especially',es:'especialmente',fr:'surtout',de:'besonders',it:'specialmente'},
  'infelizmente':{en:'unfortunately',es:'desafortunadamente',fr:'malheureusement',de:'leider',it:'sfortunatamente'},
  'felizmente':{en:'fortunately',es:'afortunadamente',fr:'heureusement',de:'glücklicherweise',it:'fortunatamente'},
  'inevitavelmente':{en:'inevitably',es:'inevitablemente',fr:'inévitablement',de:'unvermeidlich',it:'inevitabilmente'},
  'consequentemente':{en:'consequently',es:'consecuentemente',fr:'par conséquent',de:'folglich',it:'conseguentemente'},
  // Verbos comuns que faltavam
  'substituir':{en:'replace',es:'sustituir',fr:'remplacer',de:'ersetzen',it:'sostituire'},
  'estabelecer':{en:'establish',es:'establecer',fr:'établir',de:'festlegen',it:'stabilire'},
  'garantir':{en:'guarantee',es:'garantir',fr:'garantir',de:'garantieren',it:'garantire'},
  'assegurar':{en:'ensure',es:'asegurar',fr:'assurer',de:'sicherstellen',it:'assicurare'},
  'definir':{en:'define',es:'definir',fr:'définir',de:'definieren',it:'definire'},
  'considerar':{en:'consider',es:'considerar',fr:'considérer',de:'betrachten',it:'considerare'},
  'contribuir':{en:'contribute',es:'contribuir',fr:'contribuer',de:'beitragen',it:'contribuire'},
  'exigir':{en:'require',es:'exigir',fr:'exiger',de:'erfordern',it:'esigere'},
  'indicar':{en:'indicate',es:'indicar',fr:'indiquer',de:'angeben',it:'indicare'},
  'sugerir':{en:'suggest',es:'sugerir',fr:'suggérer',de:'vorschlagen',it:'suggerire'},
  'recomendar':{en:'recommend',es:'recomendar',fr:'recommander',de:'empfehlen',it:'raccomandare'},
  'solicitar':{en:'request',es:'solicitar',fr:'demander',de:'anfordern',it:'richiedere'},
  'permitir':{en:'allow',es:'permitir',fr:'permettre',de:'erlauben',it:'permettere'},
  'proibir':{en:'forbid',es:'prohibir',fr:'interdire',de:'verbieten',it:'proibire'},
  'negar':{en:'deny',es:'negar',fr:'nier',de:'leugnen',it:'negare'},
  'admitir':{en:'admit',es:'admitir',fr:'admettre',de:'zugeben',it:'ammettere'},
  'reconhecer':{en:'recognize',es:'reconocer',fr:'reconnaître',de:'anerkennen',it:'riconoscere'},
  'medir':{en:'measure',es:'medir',fr:'mesurer',de:'messen',it:'misurare'},
  'calcular':{en:'calculate',es:'calcular',fr:'calculer',de:'berechnen',it:'calcolare'},
  'analisar':{en:'analyze',es:'analizar',fr:'analyser',de:'analysieren',it:'analizzare'},
  'interpretar':{en:'interpret',es:'interpretar',fr:'interpréter',de:'interpretieren',it:'interpretare'},
  'descrever':{en:'describe',es:'describir',fr:'décrire',de:'beschreiben',it:'descrivere'},
  'explicar':{en:'explain',es:'explicar',fr:'expliquer',de:'erklären',it:'spiegare'},
  'defender':{en:'defend',es:'defender',fr:'défendre',de:'verteidigen',it:'difendere'},
  'apoiar':{en:'support',es:'apoyar',fr:'soutenir',de:'unterstützen',it:'appoggiare'},
  'competir':{en:'compete',es:'competir',fr:'concourir',de:'konkurrieren',it:'competere'},
  'comparar':{en:'compare',es:'comparar',fr:'comparer',de:'vergleichen',it:'confrontare'},
  // Adjetivos compostos que faltavam
  'sistêmico':{en:'systemic',es:'sistémico',fr:'systémique',de:'systemisch',it:'sistemico'},
  'fundamental':{en:'fundamental',es:'fundamental',fr:'fondamental',de:'grundlegend',it:'fondamentale'},
  // Substantivos abstratos
  // Verbos conjugados que faltavam
  // Verbos infinitivos comuns

  // ── Gírias e linguagem informal brasileira ──
  'bora':{en:"let's go",es:'vamos',fr:'allons-y',de:'los gehts',it:'andiamo'},
  'tô':{en:'I am',es:'estoy',fr:'je suis',de:'ich bin',it:'sono'},
  'tá':{en:'is',es:'está',fr:'est',de:'ist',it:'è'},
  'cara':{en:'dude',es:'carnal',fr:'mec',de:'Typ',it:'ragazzo'},
  'mano':{en:'bro',es:'carnal',fr:'frère',de:'Bruder',it:'fratello'},
  'véi':{en:'old man',es:'viejo',fr:'vieux',de:'alter Mann',it:'vecchio'},
  'pô':{en:'man',es:'hombre',fr:'homme',de:'Mann',it:'uomo'},
  'beleza':{en:'alright',es:'belleza',fr:'beauté',de:'Schönheit',it:'bellezza'},
  'legal':{en:'cool',es:'legal',fr:'sympa',de:'cool',it:'figo'},
  'massinha':{en:'awesome',es:'increíble',fr:'génial',de:'großartig',it:'fantastico'},
  'dahora':{en:'awesome',es:'genial',fr:'génial',de:'großartig',it:'fantastico'},
  'sacar':{en:'understand',es:'entender',fr:'comprendre',de:'begreifen',it:'capire'},
  'manter':{en:'keep',es:'mantener',fr:'garder',de:'halten',it:'mantenere'},
  'tipo':{en:'like',es:'tipo',fr:'comme',de:'wie',it:'tipo'},
  'sabe':{en:'you know',es:'sabes',fr:'tu sais',de:'weißt du',it:'sai'},
  'entendeu':{en:'understood',es:'entendido',fr:'compris',de:'verstanden',it:'capito'},
  'uai':{en:'wow',es:'vaya',fr:'oh là là',de:'wow',it:'wow'},
  'oxe':{en:'wow',es:'vaya',fr:'oh là là',de:'wow',it:'wow'},
  'oba':{en:'yay',es:'guau',fr:'ouais',de:'juhu',it:'evviva'},
  'eita':{en:'wow',es:'vaya',fr:'oh la la',de:'wow',it:'wow'},
  'rapaz':{en:'wow',es:'vaya',fr:'oh là là',de:'wow',it:'wow'},
  'caraca':{en:'wow',es:'vaya',fr:'oh là là',de:'wow',it:'wow'},
  'puxa':{en:'wow',es:'vaya',fr:'oh là là',de:'wow',it:'wow'},
  'bro':{en:'bro',es:'carnal',fr:'frère',de:'Bruder',it:'fratello'},
  'dude':{en:'dude',es:'carnal',fr:'mec',de:'Typ',it:'ragazzo'},
  'maneiro':{en:'cool',es:'genial',fr:'génial',de:'cool',it:'figo'},
  'top':{en:'top',es:'genial',fr:'génial',de:'top',it:'top'},
  'show':{en:'awesome',es:'genial',fr:'génial',de:'super',it:'fantastico'},
  'irado':{en:'awesome',es:'increíble',fr:'génial',de:'großartig',it:'fantastico'},
  'bacana':{en:'cool',es:'genial',fr:'sympa',de:'cool',it:'figo'},
  'sinistro':{en:'awesome',es:'increíble',fr:'génial',de:'großartig',it:'fantastico'},
  'zica':{en:'bad luck',es:'mala suerte',fr:'mauvaise chance',de:'Pech',it:'sfortuna'},
  'fraco':{en:'weak',es:'débil',fr:'faible',de:'schwach',it:'debole'},
  'fortão':{en:'strong guy',es:'tipazo',fr:'costaud',de:'starker Typ',it:'fattone'},
  'marronzão':{en:'cool thing',es:'genial',fr:'chouette',de:'cool',it:'figo'},
  'mohó':{en:'lame',es:'aburrido',fr:'nul',de:'lahm',it:'noioso'},
  'broca':{en:'boring',es:'aburrido',fr:'ennuyeux',de:'langweilig',it:'noioso'},
  'mó':{en:'very',es:'muy',fr:'très',de:'sehr',it:'molto'},
  'uai':{en:'well',es:'pues',fr:'eh bien',de:'naja',it:'beh'},
  'oxe':{en:'wow',es:'vaya',fr:'wow',de:'wow',it:'wow'},
  'oba':{en:'yay',es:'guau',fr:'ouais',de:'juhu',it:'evviva'},
  'eita':{en:'wow',es:'vaya',fr:'wow',de:'wow',it:'wow'},
  'rapaz':{en:'wow',es:'vaya',fr:'wow',de:'wow',it:'wow'},
  'caraca':{en:'wow',es:'vaya',fr:'wow',de:'wow',it:'wow'},
  'puxa':{en:'wow',es:'vaya',fr:'wow',de:'wow',it:'wow'},
  'mano':{en:'bro',es:'carnal',fr:'frère',de:'Bruder',it:'fratello'},
  'véi':{en:'dude',es:'viejo',fr:'vieux',de:'Alter',it:'vecchio'},
  'mermão':{en:'bro',es:'carnal',fr:'frère',de:'Bruder',it:'fratello'},
  'broca':{en:'boring',es:'aburrido',fr:'ennuyeux',de:'langweilig',it:'noioso'},
  'mó':{en:'very',es:'muy',fr:'très',de:'sehr',it:'molto'},
  'uai':{en:'well',es:'pues',fr:'alors',de:'naja',it:'beh'},
  'oxe':{en:'wow',es:'vaya',fr:'wow',de:'wow',it:'wow'},
  'oba':{en:'yay',es:'guau',fr:'ouais',de:'juhu',it:'evviva'},
  'eita':{en:'wow',es:'vaya',fr:'wow',de:'wow',it:'wow'},
  'rapaz':{en:'wow',es:'vaya',fr:'wow',de:'wow',it:'wow'},
  'caraca':{en:'wow',es:'vaya',fr:'wow',de:'wow',it:'wow'},
  'puxa':{en:'wow',es:'vaya',fr:'wow',de:'wow',it:'wow'},
  // Verbos conjugados chat
  'treinei':{en:'trained',es:'entrené',fr:'entraînai',de:'trainierte',it:'allenai'},
  'queimo':{en:'burn',es:'quemo',fr:'brûle',de:'verbrenne',it:'brucio'},
  'travando':{en:'freezing',es:'trabando',fr:'bloqué',de:'einfrieren',it:'bloccato'},
  'registrar':{en:'register',es:'registrar',fr:'enregistrer',de:'registrieren',it:'registrare'},
  'flexões':{en:'push-ups',es:'flexiones',fr:'pompes',de:'Liegestütze',it:'piegamenti'},
  'agachamentos':{en:'squats',es:'sentadillas',fr:'squats',de:'Kniebeugen',it:'squat'},
  'abdominais':{en:'crunches',es:'abdominales',fr:'abdominaux',de:'Bauchpresse',it:'addominali'},
  'à':{en:'to',es:'a',fr:'à',de:'zum',it:'al'},
};

export function applyCleanOverrides(target: Language, translations: Map<string, string>): void {
  for (const [pt, overrides] of Object.entries(CLEAN_OVERRIDES)) {
    const corrected = overrides[target];
    if (corrected && translations.has(pt)) translations.set(pt, corrected);
  }
}

export function lookupPhrase(text: string, target: Language): string | null {
  const lower = text.toLowerCase().trim();
  const phrase = PHRASE_OVERRIDES[lower];
  if (phrase && phrase[target]) return phrase[target]!;
  return null;
}
