// src/core/clean-dict.ts
// Correções word-to-word para traduções contextuais erradas
// Aplicado em runtime sobre o dicionário existente

import type { Language } from './types';

// 85 correções para palavras com traduções contextuais erradas
// Chave: PT, Valor: traduções corretas word-to-word
export const CLEAN_OVERRIDES: Record<string, Partial<Record<Language, string>>> = {
  // Corpo/Humano
  'preto': { en: 'black', es: 'negro', fr: 'noir', de: 'schwarz', it: 'nero' },
  'filho': { en: 'son', es: 'hijo', fr: 'fils', de: 'Sohn', it: 'figlio' },
  'mulher': { en: 'woman', es: 'mujer', fr: 'femme', de: 'Frau', it: 'donna' },
  'homem': { en: 'man', es: 'hombre', fr: 'homme', de: 'Mann', it: 'uomo' },
  'criança': { en: 'child', es: 'niño', fr: 'enfant', de: 'Kind', it: 'bambino' },
  'olho': { en: 'eye', es: 'ojo', fr: 'œil', de: 'Auge', it: 'occhio' },
  'mão': { en: 'hand', es: 'mano', fr: 'main', de: 'Hand', it: 'mano' },
  'pé': { en: 'foot', es: 'pie', fr: 'pied', de: 'Fuß', it: 'piede' },
  'cabeça': { en: 'head', es: 'cabeza', fr: 'tête', de: 'Kopf', it: 'testa' },
  'boca': { en: 'mouth', es: 'boca', fr: 'bouche', de: 'Mund', it: 'bocca' },
  'orelha': { en: 'ear', es: 'oreja', fr: 'oreille', de: 'Ohr', it: 'orecchio' },
  'nariz': { en: 'nose', es: 'nariz', fr: 'nez', de: 'Nase', it: 'naso' },
  'dente': { en: 'tooth', es: 'diente', fr: 'dent', de: 'Zahn', it: 'dente' },
  'língua': { en: 'tongue', es: 'lengua', fr: 'langue', de: 'Zunge', it: 'lingua' },
  'pescoço': { en: 'neck', es: 'cuello', fr: 'cou', de: 'Nacken', it: 'collo' },
  'ombro': { en: 'shoulder', es: 'hombro', fr: 'épaule', de: 'Schulter', it: 'spalla' },
  'braço': { en: 'arm', es: 'brazo', fr: 'bras', de: 'Arm', it: 'braccio' },
  'perna': { en: 'leg', es: 'pierna', fr: 'jambe', de: 'Bein', it: 'gamba' },
  'joelho': { en: 'knee', es: 'rodilla', fr: 'genou', de: 'Knie', it: 'ginocchio' },
  'costas': { en: 'back', es: 'espalda', fr: 'dos', de: 'Rücken', it: 'schiena' },
  'peito': { en: 'chest', es: 'pecho', fr: 'poitrine', de: 'Brust', it: 'petto' },
  'estômago': { en: 'stomach', es: 'estómago', fr: 'estomac', de: 'Magen', it: 'stomaco' },
  'coração': { en: 'heart', es: 'corazón', fr: 'coeur', de: 'Herz', it: 'cuore' },
  'cérebro': { en: 'brain', es: 'cerebro', fr: 'cerveau', de: 'Gehirn', it: 'cervello' },
  'sangue': { en: 'blood', es: 'sangre', fr: 'sang', de: 'Blut', it: 'sangue' },
  'osso': { en: 'bone', es: 'hueso', fr: 'os', de: 'Knochen', it: 'osso' },
  'músculo': { en: 'muscle', es: 'músculo', fr: 'muscle', de: 'Muskel', it: 'muscolo' },
  'pele': { en: 'skin', es: 'piel', fr: 'peau', de: 'Haut', it: 'pelle' },
  'cabelo': { en: 'hair', es: 'cabello', fr: 'cheveux', de: 'Haar', it: 'capello' },
  // Natureza
  'água': { en: 'water', es: 'agua', fr: 'eau', de: 'Wasser', it: 'acqua' },
  'fogo': { en: 'fire', es: 'fuego', fr: 'feu', de: 'Feuer', it: 'fuoco' },
  'terra': { en: 'earth', es: 'tierra', fr: 'terre', de: 'Erde', it: 'terra' },
  'ar': { en: 'air', es: 'aire', fr: 'air', de: 'Luft', it: 'aria' },
  'sol': { en: 'sun', es: 'sol', fr: 'soleil', de: 'Sonne', it: 'sole' },
  'lua': { en: 'moon', es: 'luna', fr: 'lune', de: 'Mond', it: 'luna' },
  'estrela': { en: 'star', es: 'estrella', fr: 'étoile', de: 'Stern', it: 'stella' },
  'nuvem': { en: 'cloud', es: 'nube', fr: 'nuage', de: 'Wolke', it: 'nuvola' },
  'vento': { en: 'wind', es: 'viento', fr: 'vent', de: 'Wind', it: 'vento' },
  'chuva': { en: 'rain', es: 'lluvia', fr: 'pluie', de: 'Regen', it: 'pioggia' },
  'neve': { en: 'snow', es: 'nieve', fr: 'neige', de: 'Schnee', it: 'neve' },
  'pedra': { en: 'stone', es: 'piedra', fr: 'pierre', de: 'Stein', it: 'pietra' },
  'montanha': { en: 'mountain', es: 'montaña', fr: 'montagne', de: 'Berg', it: 'montagna' },
  'rio': { en: 'river', es: 'río', fr: 'rivière', de: 'Fluss', it: 'fiume' },
  'mar': { en: 'sea', es: 'mar', fr: 'mer', de: 'Meer', it: 'mare' },
  'floresta': { en: 'forest', es: 'bosque', fr: 'forêt', de: 'Wald', it: 'foresta' },
  'pedra': { en: 'rock', es: 'roca', fr: 'rocher', de: 'Fels', it: 'roccia' },
  // Comida
  'comida': { en: 'food', es: 'comida', fr: 'nourriture', de: 'Essen', it: 'cibo' },
  'carne': { en: 'meat', es: 'carne', fr: 'viande', de: 'Fleisch', it: 'carne' },
  'fruta': { en: 'fruit', es: 'fruta', fr: 'fruit', de: 'Obst', it: 'frutta' },
  'legume': { en: 'vegetable', es: 'verdura', fr: 'légume', de: 'Gemüse', it: 'verdura' },
  'pão': { en: 'bread', es: 'pan', fr: 'pain', de: 'Brot', it: 'pane' },
  'leite': { en: 'milk', es: 'leche', fr: 'lait', de: 'Milch', it: 'latte' },
  'ovo': { en: 'egg', es: 'huevo', fr: 'œuf', de: 'Ei', it: 'uovo' },
  'arroz': { en: 'rice', es: 'arroz', fr: 'riz', de: 'Reis', it: 'riso' },
  'feijão': { en: 'beans', es: 'frijoles', fr: 'haricots', de: 'Bohnen', it: 'fagioli' },
  'queijo': { en: 'cheese', es: 'queso', fr: 'fromage', de: 'Käse', it: 'formaggio' },
  'frango': { en: 'chicken', es: 'pollo', fr: 'poulet', de: 'Hähnchen', it: 'pollo' },
  'peixe': { en: 'fish', es: 'pescado', fr: 'poisson', de: 'Fisch', it: 'pesce' },
  'sal': { en: 'salt', es: 'sal', fr: 'sel', de: 'Salz', it: 'sale' },
  'açúcar': { en: 'sugar', es: 'azúcar', fr: 'sucre', de: 'Zucker', it: 'zucchero' },
  'café': { en: 'coffee', es: 'café', fr: 'café', de: 'Kaffee', it: 'caffè' },
  'vinho': { en: 'wine', es: 'vino', fr: 'vin', de: 'Wein', it: 'vino' },
  'cerveja': { en: 'beer', es: 'cerveza', fr: 'bière', de: 'Bier', it: 'birra' },
  // Casa/Objetos
  'casa': { en: 'house', es: 'casa', fr: 'maison', de: 'Haus', it: 'casa' },
  'porta': { en: 'door', es: 'puerta', fr: 'porte', de: 'Tür', it: 'porta' },
  'janela': { en: 'window', es: 'ventana', fr: 'fenêtre', de: 'Fenster', it: 'finestra' },
  'mesa': { en: 'table', es: 'mesa', fr: 'table', de: 'Tisch', it: 'tavolo' },
  'cadeira': { en: 'chair', es: 'silla', fr: 'chaise', de: 'Stuhl', it: 'sedia' },
  'cama': { en: 'bed', es: 'cama', fr: 'lit', de: 'Bett', it: 'letto' },
  'carro': { en: 'car', es: 'coche', fr: 'voiture', de: 'Auto', it: 'macchina' },
  'rua': { en: 'street', es: 'calle', fr: 'rue', de: 'Straße', it: 'strada' },
  'sapato': { en: 'shoe', es: 'zapato', fr: 'chaussure', de: 'Schuh', it: 'scarpa' },
  'camisa': { en: 'shirt', es: 'camisa', fr: 'chemise', de: 'Hemd', it: 'camicia' },
  'livro': { en: 'book', es: 'libro', fr: 'livre', de: 'Buch', it: 'libro' },
  // Conceitos
  'dinheiro': { en: 'money', es: 'dinero', fr: 'argent', de: 'Geld', it: 'denaro' },
  'tempo': { en: 'time', es: 'tiempo', fr: 'temps', de: 'Zeit', it: 'tempo' },
  'vida': { en: 'life', es: 'vida', fr: 'vie', de: 'Leben', it: 'vita' },
  'trabalho': { en: 'work', es: 'trabajo', fr: 'travail', de: 'Arbeit', it: 'lavoro' },
  'escola': { en: 'school', es: 'escuela', fr: 'école', de: 'Schule', it: 'scuola' },
  'lugar': { en: 'place', es: 'lugar', fr: 'lieu', de: 'Ort', it: 'luogo' },
  'amor': { en: 'love', es: 'amor', fr: 'amour', de: 'Liebe', it: 'amore' },
  'morte': { en: 'death', es: 'muerte', fr: 'mort', de: 'Tod', it: 'morte' },

  // ── PRONOMES (faltavam do dicionário) ──────────────────
  'eu': { en: 'I', es: 'yo', fr: 'je', de: 'ich', it: 'io' },
  'tu': { en: 'you', es: 'tú', fr: 'tu', de: 'du', it: 'tu' },
  'ele': { en: 'he', es: 'él', fr: 'il', de: 'er', it: 'lui' },
  'ela': { en: 'she', es: 'ella', fr: 'elle', de: 'sie', it: 'lei' },
  'nós': { en: 'we', es: 'nosotros', fr: 'nous', de: 'wir', it: 'noi' },
  'vocês': { en: 'you', es: 'ustedes', fr: 'vous', de: 'ihr', it: 'voi' },
  'eles': { en: 'they', es: 'ellos', fr: 'ils', de: 'sie', it: 'loro' },
  'elas': { en: 'they', es: 'ellas', fr: 'elles', de: 'sie', it: 'loro' },
  'mim': { en: 'me', es: 'mí', fr: 'moi', de: 'mich', it: 'me' },
  'ti': { en: 'you', es: 'ti', fr: 'toi', de: 'dich', it: 'te' },
  'si': { en: 'himself', es: 'sí', fr: 'lui-même', de: 'sich', it: 'sé' },
  'nós': { en: 'us', es: 'nos', fr: 'nous', de: 'uns', it: 'noi' },
  'vocês': { en: 'you all', es: 'ustedes', fr: 'vous tous', de: 'ihr alle', it: 'voi tutti' },
  'eles': { en: 'them', es: 'ellos', fr: 'eux', de: 'sie', it: 'loro' },
  'elas': { en: 'them', es: 'ellas', fr: 'elles', de: 'sie', it: 'loro' },

  // ── ARTIGOS (faltavam ou errados) ─────────────────────
  'o': { en: 'the', es: 'el', fr: 'le', de: 'der', it: 'il' },
  'a': { en: 'the', es: 'la', fr: 'la', de: 'die', it: 'la' },
  'os': { en: 'the', es: 'los', fr: 'les', de: 'die', it: 'gli' },
  'as': { en: 'the', es: 'las', fr: 'les', de: 'die', it: 'le' },
  'um': { en: 'a', es: 'un', fr: 'un', de: 'ein', it: 'un' },
  'uma': { en: 'a', es: 'una', fr: 'une', de: 'eine', it: 'una' },
  'uns': { en: 'some', es: 'unos', fr: 'des', de: 'einige', it: 'dei' },
  'umas': { en: 'some', es: 'unas', fr: 'des', de: 'einige', it: 'delle' },

  // ── PREPOSIÇÕES (faltavam) ─────────────────────────────
  'de': { en: 'of', es: 'de', fr: 'de', de: 'von', it: 'di' },
  'em': { en: 'in', es: 'en', fr: 'dans', de: 'in', it: 'in' },
  'para': { en: 'for', es: 'para', fr: 'pour', de: 'für', it: 'per' },
  'com': { en: 'with', es: 'con', fr: 'avec', de: 'mit', it: 'con' },
  'sem': { en: 'without', es: 'sin', fr: 'sans', de: 'ohne', it: 'senza' },
  'por': { en: 'by', es: 'por', fr: 'par', de: 'von', it: 'da' },
  'sobre': { en: 'about', es: 'sobre', fr: 'sur', de: 'über', it: 'su' },
  'entre': { en: 'between', es: 'entre', fr: 'entre', de: 'zwischen', it: 'tra' },
  'até': { en: 'until', es: 'hasta', fr: "jusqu'à", de: 'bis', it: 'fino' },
  'desde': { en: 'from', es: 'desde', fr: 'depuis', de: 'seit', it: 'da' },
  'após': { en: 'after', es: 'después', fr: 'après', de: 'nach', it: 'dopo' },
  'antes': { en: 'before', es: 'antes', fr: 'avant', de: 'vor', it: 'prima' },
  'contra': { en: 'against', es: 'contra', fr: 'contre', de: 'gegen', it: 'contro' },
  'sob': { en: 'under', es: 'bajo', fr: 'sous', de: 'unter', it: 'sotto' },

  // ── CONJUNÇÕES ─────────────────────────────────────────
  'e': { en: 'and', es: 'y', fr: 'et', de: 'und', it: 'e' },
  'ou': { en: 'or', es: 'o', fr: 'ou', de: 'oder', it: 'o' },
  'mas': { en: 'but', es: 'pero', fr: 'mais', de: 'aber', it: 'ma' },
  'porque': { en: 'because', es: 'porque', fr: 'parce que', de: 'weil', it: 'perché' },
  'se': { en: 'if', es: 'si', fr: 'si', de: 'wenn', it: 'se' },
  'quando': { en: 'when', es: 'cuando', fr: 'quand', de: 'wenn', it: 'quando' },
  'onde': { en: 'where', es: 'donde', fr: 'où', de: 'wo', it: 'dove' },
  'como': { en: 'how', es: 'cómo', fr: 'comment', de: 'wie', it: 'come' },
  'porém': { en: 'however', es: 'sin embargo', fr: 'cependant', de: 'jedoch', it: 'tuttavia' },

  // ── ADVÉRBIOS ──────────────────────────────────────────
  'sim': { en: 'yes', es: 'sí', fr: 'oui', de: 'ja', it: 'sì' },
  'não': { en: 'no', es: 'no', fr: 'non', de: 'nein', it: 'no' },
  'aqui': { en: 'here', es: 'aquí', fr: 'ici', de: 'hier', it: 'qui' },
  'ali': { en: 'there', es: 'allí', fr: 'là', de: 'dort', it: 'lì' },
  'agora': { en: 'now', es: 'ahora', fr: 'maintenant', de: 'jetzt', it: 'adesso' },
  'depois': { en: 'after', es: 'después', fr: 'ensuite', de: 'danach', it: 'dopo' },
  'antes': { en: 'before', es: 'antes', fr: 'avant', de: 'vorher', it: 'prima' },
  'bem': { en: 'well', es: 'bien', fr: 'bien', de: 'gut', it: 'bene' },
  'mal': { en: 'badly', es: 'mal', fr: 'mal', de: 'schlecht', it: 'male' },
  'mais': { en: 'more', es: 'más', fr: 'plus', de: 'mehr', it: 'più' },
  'menos': { en: 'less', es: 'menos', fr: 'moins', de: 'weniger', it: 'meno' },
  'muito': { en: 'very', es: 'muy', fr: 'très', de: 'sehr', it: 'molto' },
  'pouco': { en: 'little', es: 'poco', fr: 'peu', de: 'wenig', it: 'poco' },
  'também': { en: 'also', es: 'también', fr: 'aussi', de: 'auch', it: 'anche' },
  'ainda': { en: 'still', es: 'todavía', fr: 'encore', de: 'noch', it: 'ancora' },
  'já': { en: 'already', es: 'ya', fr: 'déjà', de: 'schon', it: 'già' },
  'hoje': { en: 'today', es: 'hoy', fr: "aujourd'hui", de: 'heute', it: 'oggi' },
  'ontem': { en: 'yesterday', es: 'ayer', fr: 'hier', de: 'gestern', it: 'ieri' },
  'amanhã': { en: 'tomorrow', es: 'mañana', fr: 'demain', de: 'morgen', it: 'domani' },
  'sempre': { en: 'always', es: 'siempre', fr: 'toujours', de: 'immer', it: 'sempre' },
  'nunca': { en: 'never', es: 'nunca', fr: 'jamais', de: 'nie', it: 'mai' },
  'talvez': { en: 'maybe', es: 'tal vez', fr: 'peut-être', de: 'vielleicht', it: 'forse' },

  // ── VERBOS AUXILIARES ─────────────────────────────────
  'é': { en: 'is', es: 'es', fr: 'est', de: 'ist', it: 'è' },
  'são': { en: 'are', es: 'son', fr: 'sont', de: 'sind', it: 'sono' },
  'está': { en: 'is', es: 'está', fr: 'est', de: 'ist', it: 'è' },
  'estão': { en: 'are', es: 'están', fr: 'sont', de: 'sind', it: 'sono' },
  'foi': { en: 'was', es: 'fue', fr: 'était', de: 'war', it: 'fu' },
  'foram': { en: 'were', es: 'fueron', fr: 'étaient', de: 'waren', it: 'furono' },
  'tem': { en: 'has', es: 'tiene', fr: 'a', de: 'hat', it: 'ha' },
  'têm': { en: 'have', es: 'tienen', fr: 'ont', de: 'haben', it: 'hanno' },
  'tinha': { en: 'had', es: 'tenía', fr: 'avait', de: 'hatte', it: 'aveva' },
  'faz': { en: 'does', es: 'hace', fr: 'fait', de: 'macht', it: 'fa' },
  'fazia': { en: 'did', es: 'hacía', fr: 'faisait', de: 'machte', it: 'faceva' },
  'pode': { en: 'can', es: 'puede', fr: 'peut', de: 'kann', it: 'può' },
  'devia': { en: 'should', es: 'debería', fr: 'devrait', de: 'sollte', it: 'dovrebbe' },

  // ── NÚMEROS ────────────────────────────────────────────
  'um': { en: 'one', es: 'uno', fr: 'un', de: 'eins', it: 'uno' },
  'dois': { en: 'two', es: 'dos', fr: 'deux', de: 'zwei', it: 'due' },
  'três': { en: 'three', es: 'tres', fr: 'trois', de: 'drei', it: 'tre' },
  'quatro': { en: 'four', es: 'cuatro', fr: 'quatre', de: 'vier', it: 'quattro' },
  'cinco': { en: 'five', es: 'cinco', fr: 'cinq', de: 'fünf', it: 'cinque' },
  'seis': { en: 'six', es: 'seis', fr: 'six', de: 'sechs', it: 'sei' },
  'sete': { en: 'seven', es: 'siete', fr: 'sept', de: 'sieben', it: 'sette' },
  'oito': { en: 'eight', es: 'ocho', fr: 'huit', de: 'acht', it: 'otto' },
  'nove': { en: 'nine', es: 'nueve', fr: 'neuf', de: 'neun', it: 'nove' },
  'dez': { en: 'ten', es: 'diez', fr: 'dix', de: 'zehn', it: 'dieci' },
};

/**
 * Aplica correções word-to-word sobre um mapa de tradução.
 * Modifica o mapa in-place para corrigir traduções contextuais erradas.
 */
export function applyCleanOverrides(target: Language, translations: Map<string, string>): void {
  for (const [pt, overrides] of Object.entries(CLEAN_OVERRIDES)) {
    const corrected = overrides[target];
    if (corrected && translations.has(pt)) {
      translations.set(pt, corrected);
    }
  }
}
