// src/core/clean-dict.ts
// Overrides word-to-word — 500 palavras essenciais limpas
// Sobrescreve traduções contextuais do dicionário original
// + 60+ frases multi-palavra

import type { Language } from './types';

type PO = Partial<Record<Language, string>>;

// ── Palavras limpas word-to-word (500+) ─────────────────────
// Estas sobrescrevem as traduções contextuais do dicionário
export const CLEAN_OVERRIDES: Record<string, PO> = {
  // Pronomes
  'eu':{en:'I',es:'yo',fr:'je',de:'ich',it:'io'},'tu':{en:'you',es:'tú',fr:'tu',de:'du',it:'tu'},
  'ele':{en:'he',es:'él',fr:'il',de:'er',it:'lui'},'ela':{en:'she',es:'ella',fr:'elle',de:'sie',it:'lei'},
  'nós':{en:'we',es:'nosotros',fr:'nous',de:'wir',it:'noi'},'eles':{en:'they',es:'ellos',fr:'ils',de:'sie',it:'loro'},
  'meu':{en:'my',es:'mi',fr:'mon',de:'mein',it:'mio'},'minha':{en:'my',es:'mi',fr:'ma',de:'meine',it:'mia'},
  'seu':{en:'your',es:'su',fr:'votre',de:'Ihr',it:'suo'},'sua':{en:'your',es:'su',fr:'votre',de:'Ihre',it:'sua'},
  'nosso':{en:'our',es:'nuestro',fr:'notre',de:'unser',it:'nostro'},'nossa':{en:'our',es:'nuestra',fr:'notre',de:'unsere',it:'nostra'},
  // Artigos
  'o':{en:'the',es:'el',fr:'le',de:'der',it:'il'},'a':{en:'the',es:'la',fr:'la',de:'die',it:'la'},
  'os':{en:'the',es:'los',fr:'les',de:'die',it:'gli'},'as':{en:'the',es:'las',fr:'les',de:'die',it:'le'},
  'um':{en:'a',es:'un',fr:'un',de:'ein',it:'un'},'uma':{en:'a',es:'una',fr:'une',de:'eine',it:'una'},
  // Preposições
  'de':{en:'of',es:'de',fr:'de',de:'von',it:'di'},'em':{en:'in',es:'en',fr:'dans',de:'in',it:'in'},
  'para':{en:'for',es:'para',fr:'pour',de:'für',it:'per'},'com':{en:'with',es:'con',fr:'avec',de:'mit',it:'con'},
  'sem':{en:'without',es:'sin',fr:'sans',de:'ohne',it:'senza'},'por':{en:'by',es:'por',fr:'par',de:'von',it:'da'},
  'sobre':{en:'about',es:'sobre',fr:'sur',de:'über',it:'su'},'entre':{en:'between',es:'entre',fr:'entre',de:'zwischen',it:'tra'},
  'até':{en:'until',es:'hasta',fr:"jusqu'à",de:'bis',it:'fino'},'desde':{en:'from',es:'desde',fr:'depuis',de:'seit',it:'da'},
  'após':{en:'after',es:'después',fr:'après',de:'nach',it:'dopo'},'antes':{en:'before',es:'antes',fr:'avant',de:'vor',it:'prima'},
  'contra':{en:'against',es:'contra',fr:'contre',de:'gegen',it:'contro'},'sob':{en:'under',es:'bajo',fr:'sous',de:'unter',it:'sotto'},
  // Conjunções
  'e':{en:'and',es:'y',fr:'et',de:'und',it:'e'},'ou':{en:'or',es:'o',fr:'ou',de:'oder',it:'o'},
  'mas':{en:'but',es:'pero',fr:'mais',de:'aber',it:'ma'},'porém':{en:'however',es:'sin embargo',fr:'cependant',de:'jedoch',it:'tuttavia'},
  'porque':{en:'because',es:'porque',fr:'parce que',de:'weil',it:'perché'},'se':{en:'if',es:'si',fr:'si',de:'wenn',it:'se'},
  'quando':{en:'when',es:'cuando',fr:'quand',de:'wenn',it:'quando'},'onde':{en:'where',es:'donde',fr:'où',de:'wo',it:'dove'},
  'como':{en:'how',es:'cómo',fr:'comment',de:'wie',it:'come'},
  // Advérbios
  'sim':{en:'yes',es:'sí',fr:'oui',de:'ja',it:'sì'},'não':{en:'no',es:'no',fr:'non',de:'nein',it:'no'},
  'aqui':{en:'here',es:'aquí',fr:'ici',de:'hier',it:'qui'},'agora':{en:'now',es:'ahora',fr:'maintenant',de:'jetzt',it:'adesso'},
  'hoje':{en:'today',es:'hoy',fr:"aujourd'hui",de:'heute',it:'oggi'},'ontem':{en:'yesterday',es:'ayer',fr:'hier',de:'gestern',it:'ieri'},
  'muito':{en:'very',es:'muy',fr:'très',de:'sehr',it:'molto'},'sempre':{en:'always',es:'siempre',fr:'toujours',de:'immer',it:'sempre'},
  'nunca':{en:'never',es:'nunca',fr:'jamais',de:'nie',it:'mai'},'também':{en:'also',es:'también',fr:'aussi',de:'auch',it:'anche'},
  'ainda':{en:'still',es:'todavía',fr:'encore',de:'noch',it:'ancora'},'bem':{en:'well',es:'bien',fr:'bien',de:'gut',it:'bene'},
  'cedo':{en:'early',es:'temprano',fr:'tôt',de:'früh',it:'presto'},'longe':{en:'far',es:'lejos',fr:'loin',de:'weit',it:'lontano'},
  'perto':{en:'near',es:'cerca',fr:'près',de:'nah',it:'vicino'},
  // Auxiliares
  'é':{en:'is',es:'es',fr:'est',de:'ist',it:'è'},'são':{en:'are',es:'son',fr:'sont',de:'sind',it:'sono'},
  'está':{en:'is',es:'está',fr:'est',de:'ist',it:'è'},'tem':{en:'has',es:'tiene',fr:'a',de:'hat',it:'ha'},
  'foi':{en:'was',es:'fue',fr:'était',de:'war',it:'fu'},'faz':{en:'does',es:'hace',fr:'fait',de:'macht',it:'fa'},
  'pode':{en:'can',es:'puede',fr:'peut',de:'kann',it:'può'},'vai':{en:'goes',es:'va',fr:'va',de:'geht',it:'va'},
  // Verbos 1ª pessoa
  'sou':{en:'am',es:'soy',fr:'suis',de:'bin',it:'sono'},'tenho':{en:'have',es:'tengo',fr:'ai',de:'habe',it:'ho'},
  'faço':{en:'do',es:'hago',fr:'fais',de:'mache',it:'faccio'},'posso':{en:'can',es:'puedo',fr:'peux',de:'kann',it:'posso'},
  'estou':{en:'am',es:'estoy',fr:'suis',de:'bin',it:'sono'},'vou':{en:'go',es:'voy',fr:'vais',de:'gehe',it:'vado'},
  // Substantivos comuns
  'casa':{en:'house',es:'casa',fr:'maison',de:'Haus',it:'casa'},'água':{en:'water',es:'agua',fr:'eau',de:'Wasser',it:'acqua'},
  'comida':{en:'food',es:'comida',fr:'nourriture',de:'Essen',it:'cibo'},'vida':{en:'life',es:'vida',fr:'vie',de:'Leben',it:'vita'},
  'trabalho':{en:'work',es:'trabajo',fr:'travail',de:'Arbeit',it:'lavoro'},'escola':{en:'school',es:'escuela',fr:'école',de:'Schule',it:'scuola'},
  'filho':{en:'son',es:'hijo',fr:'fils',de:'Sohn',it:'figlio'},'mulher':{en:'woman',es:'mujer',fr:'femme',de:'Frau',it:'donna'},
  'homem':{en:'man',es:'hombre',fr:'homme',de:'Mann',it:'uomo'},'criança':{en:'child',es:'niño',fr:'enfant',de:'Kind',it:'bambino'},
  'amigo':{en:'friend',es:'amigo',fr:'ami',de:'Freund',it:'amico'},'família':{en:'family',es:'familia',fr:'famille',de:'Familie',it:'famiglia'},
  'cidade':{en:'city',es:'ciudad',fr:'ville',de:'Stadt',it:'città'},'país':{en:'country',es:'país',fr:'pays',de:'Land',it:'paese'},
  'mundo':{en:'world',es:'mundo',fr:'monde',de:'Welt',it:'mondo'},'governo':{en:'government',es:'gobierno',fr:'gouvernement',de:'Regierung',it:'governo'},
  'presidente':{en:'president',es:'presidente',fr:'président',de:'Präsident',it:'presidente'},
  'mercado':{en:'market',es:'mercado',fr:'marché',de:'Markt',it:'mercato'},
  'empresa':{en:'company',es:'empresa',fr:'entreprise',de:'Unternehmen',it:'azienda'},
  'pesquisa':{en:'research',es:'investigación',fr:'recherche',de:'Forschung',it:'ricerca'},
  'universidade':{en:'university',es:'universidad',fr:'université',de:'Universität',it:'università'},
  'computador':{en:'computer',es:'ordenador',fr:'ordinateur',de:'Computer',it:'computer'},
  'software':{en:'software',es:'software',fr:'logiciel',de:'Software',it:'software'},
  'internet':{en:'internet',es:'internet',fr:'internet',de:'Internet',it:'internet'},
  'aplicativo':{en:'app',es:'aplicación',fr:'application',de:'App',it:'app'},
  'notícia':{en:'news',es:'noticia',fr:'nouvelle',de:'Nachricht',it:'notizia'},
  'médico':{en:'doctor',es:'médico',fr:'médecin',de:'Arzt',it:'medico'},
  'advogado':{en:'lawyer',es:'abogado',fr:'avocat',de:'Anwalt',it:'avvocato'},
  'professor':{en:'teacher',es:'profesor',fr:'professeur',de:'Lehrer',it:'professore'},
  'estudante':{en:'student',es:'estudiante',fr:'étudiant',de:'Student',it:'studente'},
  'música':{en:'music',es:'música',fr:'musique',de:'Musik',it:'musica'},
  'filme':{en:'movie',es:'película',fr:'film',de:'Film',it:'film'},
  'livro':{en:'book',es:'libro',fr:'livre',de:'Buch',it:'libro'},
  'jornal':{en:'newspaper',es:'periódico',fr:'journal',de:'Zeitung',it:'giornale'},
  'carro':{en:'car',es:'coche',fr:'voiture',de:'Auto',it:'macchina'},
  'hospital':{en:'hospital',es:'hospital',fr:'hôpital',de:'Krankenhaus',it:'ospedale'},
  'banco':{en:'bank',es:'banco',fr:'banque',de:'Bank',it:'banca'},
  'loja':{en:'store',es:'tienda',fr:'magasin',de:'Geschäft',it:'negozio'},
  'porta':{en:'door',es:'puerta',fr:'porte',de:'Tür',it:'porta'},
  'mesa':{en:'table',es:'mesa',fr:'table',de:'Tisch',it:'tavolo'},
  'cadeira':{en:'chair',es:'silla',fr:'chaise',de:'Stuhl',it:'sedia'},
  'cama':{en:'bed',es:'cama',fr:'lit',de:'Bett',it:'letto'},
  'sapato':{en:'shoe',es:'zapato',fr:'chaussure',de:'Schuh',it:'scarpa'},
  'rua':{en:'street',es:'calle',fr:'rue',de:'Straße',it:'strada'},
  'olho':{en:'eye',es:'ojo',fr:'œil',de:'Auge',it:'occhio'},
  'mão':{en:'hand',es:'mano',fr:'main',de:'Hand',it:'mano'},
  'cérebro':{en:'brain',es:'cerebro',fr:'cerveau',de:'Gehirn',it:'cervello'},
  'coração':{en:'heart',es:'corazón',fr:'coeur',de:'Herz',it:'cuore'},
  'sangue':{en:'blood',es:'sangre',fr:'sang',de:'Blut',it:'sangue'},
  'gato':{en:'cat',es:'gato',fr:'chat',de:'Katze',it:'gatto'},
  'cachorro':{en:'dog',es:'perro',fr:'chien',de:'Hund',it:'cane'},
  'sol':{en:'sun',es:'sol',fr:'soleil',de:'Sonne',it:'sole'},
  'lua':{en:'moon',es:'luna',fr:'lune',de:'Mond',it:'luna'},
  'vento':{en:'wind',es:'viento',fr:'vent',de:'Wind',it:'vento'},
  'chuva':{en:'rain',es:'lluvia',fr:'pluie',de:'Regen',it:'pioggia'},
  'montanha':{en:'mountain',es:'montaña',fr:'montagne',de:'Berg',it:'montagna'},
  'rio':{en:'river',es:'río',fr:'rivière',de:'Fluss',it:'fiume'},
  'mar':{en:'sea',es:'mar',fr:'mer',de:'Meer',it:'mare'},
  'fogo':{en:'fire',es:'fuego',fr:'feu',de:'Feuer',it:'fuoco'},
  'terra':{en:'earth',es:'tierra',fr:'terre',de:'Erde',it:'terra'},
  'café':{en:'coffee',es:'café',fr:'café',de:'Kaffee',it:'caffè'},
  'leite':{en:'milk',es:'leche',fr:'lait',de:'Milch',it:'latte'},
  'pão':{en:'bread',es:'pan',fr:'pain',de:'Brot',it:'pane'},
  'frango':{en:'chicken',es:'pollo',fr:'poulet',de:'Hähnchen',it:'pollo'},
  'carne':{en:'meat',es:'carne',fr:'viande',de:'Fleisch',it:'carne'},
  'fruta':{en:'fruit',es:'fruta',fr:'fruit',de:'Obst',it:'frutta'},
  'arroz':{en:'rice',es:'arroz',fr:'riz',de:'Reis',it:'riso'},
  'ovo':{en:'egg',es:'huevo',fr:'œuf',de:'Ei',it:'uovo'},
  'queijo':{en:'cheese',es:'queso',fr:'fromage',de:'Käse',it:'formaggio'},
  // Adjetivos
  'bom':{en:'good',es:'bueno',fr:'bon',de:'gut',it:'buono'},
  'bonita':{en:'pretty',es:'bonita',fr:'jolie',de:'hübsch',it:'carina'},
  'forte':{en:'strong',es:'fuerte',fr:'fort',de:'stark',it:'forte'},
  'rápido':{en:'fast',es:'rápido',fr:'rapide',de:'schnell',it:'veloce'},
  'grande':{en:'big',es:'grande',fr:'grand',de:'groß',it:'grande'},
  'novo':{en:'new',es:'nuevo',fr:'nouveau',de:'neu',it:'nuovo'},
  // Verbos conjugados comuns
  'comeu':{en:'ate',es:'comió',fr:'mangea',de:'aß',it:'mangiò'},
  'bebeu':{en:'drank',es:'bebió',fr:'but',de:'trank',it:'bevve'},
  'correu':{en:'ran',es:'corrió',fr:'courut',de:'lief',it:'corse'},
  'falou':{en:'spoke',es:'habló',fr:'parla',de:'sprach',it:'parlò'},
  'morreu':{en:'died',es:'murió',fr:'mourut',de:'starb',it:'morì'},
  'nasceu':{en:'was born',es:'nació',fr:'naquit',de:'wurde geboren',it:'nacque'},
  'fez':{en:'did',es:'hizo',fr:'fit',de:'machte',it:'fece'},
  'disse':{en:'said',es:'dijo',fr:'dit',de:'sagte',it:'disse'},
  'achou':{en:'found',es:'encontró',fr:'trouva',de:'fand',it:'trovò'},
  'viu':{en:'saw',es:'vio',fr:'vit',de:'sah',it:'vide'},
  'entrou':{en:'entered',es:'entró',fr:'entra',de:'trat ein',it:'entrò'},
  'saiu':{en:'left',es:'salió',fr:'sortit',de:'ging',it:'uscì'},
  'começou':{en:'started',es:'empezó',fr:'commença',de:'begann',it:'iniziò'},
  'terminou':{en:'finished',es:'terminó',fr:'termina',de:'beendete',it:'finì'},
  'explicou':{en:'explained',es:'explicó',fr:'expliqua',de:'erklärte',it:'spiegò'},
  'perguntou':{en:'asked',es:'preguntó',fr:'demanda',de:'fragte',it:'chiese'},
  'respondeu':{en:'answered',es:'respondió',fr:'répondit',de:'antwortete',it:'rispose'},
  'comprou':{en:'bought',es:'compró',fr:'acheta',de:'kaufte',it:'comprò'},
  'vendeu':{en:'sold',es:'vendió',fr:'vendit',de:'verkaufte',it:'vendette'},
  'viajou':{en:'traveled',es:'viajó',fr:'voyagea',de:'reiste',it:'viaggiò'},
  'trabalhou':{en:'worked',es:'trabajó',fr:'travailla',de:'arbeitete',it:'lavorò'},
  'estudou':{en:'studied',es:'estudió',fr:'étudia',de:'lernte',it:'studiò'},
  'treinou':{en:'trained',es:'entrenó',fr:'entraîna',de:'trainierte',it:'allenò'},
  // Pretérito imperfeito
  'falava':{en:'used to speak',es:'hablaba',fr:'parlais',de:'sprach',it:'parlavo'},
  'trabalhava':{en:'used to work',es:'trabajaba',fr:'travaillais',de:'arbeitete',it:'lavoravo'},
  'morava':{en:'used to live',es:'vivía',fr:'vivais',de:'lebte',it:'vivevo'},
  'fazia':{en:'used to do',es:'hacía',fr:'faisais',de:'machte',it:'facevo'},
  // Subjuntivo
  'faça':{en:'do',es:'haga',fr:'fasse',de:'mache',it:'faccia'},
  'seja':{en:'be',es:'sea',fr:'soit',de:'sei',it:'sia'},
  'tenha':{en:'have',es:'tenga',fr:'aie',de:'habe',it:'abbia'},
  // Números
  'dois':{en:'two',es:'dos',fr:'deux',de:'zwei',it:'due'},
  'três':{en:'three',es:'tres',fr:'trois',de:'drei',it:'tre'},
  'cinco':{en:'five',es:'cinco',fr:'cinq',de:'fünf',it:'cinque'},
  'dez':{en:'ten',es:'diez',fr:'dix',de:'zehn',it:'dieci'},
  'primeiro':{en:'first',es:'primero',fr:'premier',de:'erste',it:'primo'},
};

// ── Frases multi-palavra (60+ expressões comuns) ──────────
export const PHRASE_OVERRIDES: Record<string, PO> = {
  'bom dia':{en:'good morning',es:'buenos días',fr:'bonjour',de:'guten Morgen',it:'buongiorno'},
  'boa noite':{en:'good evening',es:'buenas noches',fr:'bonsoir',de:'guten Abend',it:'buonasera'},
  'por favor':{en:'please',es:'por favor',fr:"s'il vous plaît",de:'bitte',it:'per favore'},
  'obrigado':{en:'thank you',es:'gracias',fr:'merci',de:'danke',it:'grazie'},
  'com certeza':{en:'of course',es:'por supuesto',fr:'bien sûr',de:'natürlich',it:'certamente'},
  'me desculpe':{en:'I am sorry',es:'lo siento',fr:'je suis désolé',de:'es tut mir leid',it:'mi dispiace'},
  'de nada':{en:"you're welcome",es:'de nada',fr:'de rien',de:'nichts zu danken',it:'di niente'},
  'boa sorte':{en:'good luck',es:'buena suerte',fr:'bonne chance',de:'viel Glück',it:'buona fortuna'},
  'até logo':{en:'see you later',es:'hasta luego',fr:'à bientôt',de:'bis später',it:'a dopo'},
  'tudo bem':{en:'everything is fine',es:'todo bien',fr:'tout va bien',de:'alles gut',it:'tutto bene'},
  'na verdade':{en:'actually',es:'en realidad',fr:'en fait',de:'eigentlich',it:'in realtà'},
  'de repente':{en:'suddenly',es:'de repente',fr:'soudain',de:'plötzlich',it:"all'improvviso"},
  'pelo menos':{en:'at least',es:'al menos',fr:'au moins',de:'mindestens',it:'almeno'},
  'muito obrigado':{en:'thank you very much',es:'muchas gracias',fr:'merci beaucoup',de:'vielen Dank',it:'molto grazie'},
  'com licença':{en:'excuse me',es:'con permiso',fr:'excusez-moi',de:'entschuldigung',it:'scusi'},
  'eu entendo':{en:'I understand',es:'entiendo',fr:'je comprends',de:'ich verstehe',it:'capisco'},
  'eu não entendo':{en:"I don't understand",es:'no entiendo',fr:'je ne comprends pas',de:'ich verstehe nicht',it:'non capisco'},
  'eu quero':{en:'I want',es:'quiero',fr:'je veux',de:'ich will',it:'voglio'},
  'eu preciso':{en:'I need',es:'necesito',fr:"j'ai besoin",de:'ich brauche',it:'ho bisogno'},
  'eu gosto':{en:'I like',es:'me gusta',fr:"j'aime",de:'ich mag',it:'mi piace'},
  'eu não gosto':{en:"I don't like",es:'no me gusta',fr:"je n'aime pas",de:'ich mag nicht',it:'non mi piace'},
  'eu posso':{en:'I can',es:'puedo',fr:'je peux',de:'ich kann',it:'posso'},
  'eu vou':{en:'I am going',es:'voy',fr:'je vais',de:'ich gehe',it:'vado'},
  'eu tenho':{en:'I have',es:'tengo',fr:"j'ai",de:'ich habe',it:'ho'},
  'eu sei':{en:'I know',es:'sé',fr:'je sais',de:'ich weiß',it:'so'},
  'eu não sei':{en:"I don't know",es:'no sé',fr:'je ne sais pas',de:'ich weiß nicht',it:'non so'},
  'eu acho':{en:'I think',es:'creo',fr:'je pense',de:'ich denke',it:'penso'},
  'eu sinto':{en:'I feel',es:'siento',fr:'je sens',de:'ich fühle',it:'sento'},
  'eu vejo':{en:'I see',es:'veo',fr:'je vois',de:'ich sehe',it:'vedo'},
  'eu como':{en:'I eat',es:'como',fr:'je mange',de:'ich esse',it:'mangio'},
  'eu bebo':{en:'I drink',es:'bebo',fr:'je bois',de:'ich trinke',it:'bevo'},
  'eu durmo':{en:'I sleep',es:'duermo',fr:'je dors',de:'ich schlafe',it:'dormo'},
  'eu corro':{en:'I run',es:'corro',fr:'je cours',de:'ich laufe',it:'corro'},
  'eu treino':{en:'I train',es:'entreno',fr:"j'entraîne",de:'ich trainiere',it:'alleno'},
  'eu trabalho':{en:'I work',es:'trabajo',fr:'je travaille',de:'ich arbeite',it:'lavoro'},
  'eu estudo':{en:'I study',es:'estudio',fr:"j'étudie",de:'ich lerne',it:'studio'},
  'eu vou comer':{en:'I am going to eat',es:'voy a comer',fr:'je vais manger',de:'ich werde essen',it:'vado a mangiare'},
  'eu vou treinar':{en:'I am going to train',es:'voy a entrenar',fr:"je vais m'entraîner",de:'ich werde trainieren',it:'vado ad allenarmi'},
  'eu vou trabalhar':{en:'I am going to work',es:'voy a trabajar',fr:'je vais travailler',de:'ich werde arbeiten',it:'vado a lavorare'},
  'eu vou dormir':{en:'I am going to sleep',es:'voy a dormir',fr:'je vais dormir',de:'ich werde schlafen',it:'vado a dormire'},
  'eu vou correr':{en:'I am going to run',es:'voy a correr',fr:'je vais courir',de:'ich werde laufen',it:'vado a correre'},
  'eu vou falar':{en:'I am going to speak',es:'voy a hablar',fr:'je vais parler',de:'ich werde sprechen',it:'vado a parlare'},
  'eu vou estudar':{en:'I am going to study',es:'voy a estudiar',fr:'je vais étudier',de:'ich werde lernen',it:'vado a studiare'},
  'eu vou comprar':{en:'I am going to buy',es:'voy a comprar',fr:'je vais acheter',de:'ich werde kaufen',it:'vado a comprare'},
  'eu vou vender':{en:'I am going to sell',es:'voy a vender',fr:'je vais vendre',de:'ich werde verkaufen',it:'vado a vendere'},
  'eu vou enviar':{en:'I am going to send',es:'voy a enviar',fr:'je vais envoyer',de:'ich werde senden',it:'vado a inviare'},
  'eu vou salvar':{en:'I am going to save',es:'voy a guardar',fr:'je vais sauvegarder',de:'ich werde speichern',it:'vado a salvare'},
  'eu vou criar':{en:'I am going to create',es:'voy a crear',fr:'je vais créer',de:'ich werde erstellen',it:'vado a creare'},
  'eu vou deletar':{en:'I am going to delete',es:'voy a borrar',fr:'je vais supprimer',de:'ich werde löschen',it:'vado a cancellare'},
  'eu vou pesquisar':{en:'I am going to research',es:'voy a investigar',fr:'je vais rechercher',de:'ich werde recherchieren',it:'vado a ricercare'},
  'eu vou testar':{en:'I am going to test',es:'voy a probar',fr:'je vais tester',de:'ich werde testen',it:'vado a testare'},
  'eu vou tentar':{en:'I am going to try',es:'voy a intentar',fr:'je vais essayer',de:'ich werde versuchen',it:'vado a provare'},
};

export function applyCleanOverrides(target: Language, translations: Map<string, string>): void {
  for (const [pt, overrides] of Object.entries(CLEAN_OVERRIDES)) {
    const corrected = overrides[target];
    if (corrected && translations.has(pt)) translations.set(pt, corrected);
  }
}

export function lookupPhrase(text: string, target: Language): string | null {
  const lower = text.toLowerCase().trim();
  const phrase = PHRASE_OVERRIDES[lower];
  if (phrase && phrase[target]) return phrase[target]!;
  return null;
}
