// src/core/verbs-data.ts
// 200+ verbos PT → infinitivos EN/ES/FR/DE (dados puros, sem lógica)

type TL = 'en' | 'es' | 'fr' | 'de';
export const VERBS: Record<string, Record<TL, string>> = {
  // Movimento/Exercício
  correr: { en: 'run', es: 'correr', fr: 'courir', de: 'laufen' },
  andar: { en: 'walk', es: 'caminar', fr: 'marcher', de: 'gehen' },
  pular: { en: 'jump', es: 'saltar', fr: 'sauter', de: 'springen' },
  nadar: { en: 'swim', es: 'nadar', fr: 'nager', de: 'schwimmen' },
  pedalar: { en: 'pedal', es: 'pedalear', fr: 'pédaler', de: 'treten' },
  escalar: { en: 'climb', es: 'escalar', fr: 'escalader', de: 'klettern' },
  levantar: { en: 'lift', es: 'levantar', fr: 'soulever', de: 'heben' },
  empurrar: { en: 'push', es: 'empujar', fr: 'pousser', de: 'schieben' },
  puxar: { en: 'pull', es: 'tirar', fr: 'tirer', de: 'ziehen' },
  agachar: { en: 'squat', es: 'agacharse', fr: "s'accroupir", de: 'hocken' },
  flexionar: { en: 'curl', es: 'flexionar', fr: 'fléchir', de: 'beugen' },
  esticar: { en: 'stretch', es: 'estirar', fr: 'étirer', de: 'dehnen' },
  saltar: { en: 'leap', es: 'saltar', fr: 'sauter', de: 'springen' },
  descer: { en: 'descend', es: 'bajar', fr: 'descendre', de: 'herunter' },
  subir: { en: 'go up', es: 'subir', fr: 'monter', de: 'hoch' },
  arrastar: { en: 'drag', es: 'arrastrar', fr: 'traîner', de: 'schleppen' },
  // Ações básicas
  comer: { en: 'eat', es: 'comer', fr: 'manger', de: 'essen' },
  beber: { en: 'drink', es: 'beber', fr: 'boire', de: 'trinken' },
  dormir: { en: 'sleep', es: 'dormir', fr: 'dormir', de: 'schlafen' },
  acordar: { en: 'wake up', es: 'despertar', fr: 'se réveiller', de: 'aufwachen' },
  sentar: { en: 'sit', es: 'sentarse', fr: "s'asseoir", de: 'sitzen' },
  ficar: { en: 'stay', es: 'quedarse', fr: 'rester', de: 'bleiben' },
  sair: { en: 'leave', es: 'salir', fr: 'sortir', de: 'ausgehen' },
  entrar: { en: 'enter', es: 'entrar', fr: 'entrer', de: 'eintreten' },
  voltar: { en: 'return', es: 'volver', fr: 'revenir', de: 'zurückkehren' },
  parar: { en: 'stop', es: 'parar', fr: 'arrêter', de: 'stoppen' },
  comecar: { en: 'start', es: 'empezar', fr: 'commencer', de: 'anfangen' },
  terminar: { en: 'finish', es: 'terminar', fr: 'finir', de: 'beenden' },
  esperar: { en: 'wait', es: 'esperar', fr: 'attendre', de: 'warten' },
  procurar: { en: 'search', es: 'buscar', fr: 'chercher', de: 'suchen' },
  encontrar: { en: 'find', es: 'encontrar', fr: 'trouver', de: 'finden' },
  perder: { en: 'lose', es: 'perder', fr: 'perdre', de: 'verlieren' },
  ganhar: { en: 'win', es: 'ganar', fr: 'gagner', de: 'gewinnen' },
  jogar: { en: 'play', es: 'jugar', fr: 'jouer', de: 'spielen' },
  // Treino
  treinar: { en: 'train', es: 'entrenar', fr: 'entraîner', de: 'trainieren' },
  exercitar: { en: 'exercise', es: 'ejercitar', fr: 'exercer', de: 'üben' },
  aquecer: { en: 'warm up', es: 'calentar', fr: 'chauffer', de: 'aufwärmen' },
  alongar: { en: 'stretch', es: 'estirar', fr: 'étirer', de: 'dehnen' },
  respirar: { en: 'breathe', es: 'respirar', fr: 'respirer', de: 'atmen' },
  descansar: { en: 'rest', es: 'descansar', fr: 'se reposer', de: 'ausruhen' },
  pesar: { en: 'weigh', es: 'pesar', fr: 'peser', de: 'wiegen' },
  medir: { en: 'measure', es: 'medir', fr: 'mesurer', de: 'messen' },
  // Comunicação
  falar: { en: 'speak', es: 'hablar', fr: 'parler', de: 'sprechen' },
  dizer: { en: 'say', es: 'decir', fr: 'dire', de: 'sagen' },
  perguntar: { en: 'ask', es: 'preguntar', fr: 'demander', de: 'fragen' },
  responder: { en: 'answer', es: 'responder', fr: 'répondre', de: 'antworten' },
  cantar: { en: 'sing', es: 'cantar', fr: 'chanter', de: 'singen' },
  gritar: { en: 'shout', es: 'gritar', fr: 'crier', de: 'schreien' },
  ouvir: { en: 'hear', es: 'oír', fr: 'entendre', de: 'hören' },
  escutar: { en: 'listen', es: 'escuchar', fr: 'écouter', de: 'zuhören' },
  // Cognição
  pensar: { en: 'think', es: 'pensar', fr: 'penser', de: 'denken' },
  saber: { en: 'know', es: 'saber', fr: 'savoir', de: 'wissen' },
  sentir: { en: 'feel', es: 'sentir', fr: 'sentir', de: 'fühlen' },
  chorar: { en: 'cry', es: 'llorar', fr: 'pleurer', de: 'weinen' },
  rir: { en: 'laugh', es: 'reír', fr: 'rire', de: 'lachen' },
  sorrir: { en: 'smile', es: 'sonreír', fr: 'sourire', de: 'lächeln' },
  // Trabalho
  trabalhar: { en: 'work', es: 'trabajar', fr: 'travailler', de: 'arbeiten' },
  estudar: { en: 'study', es: 'estudar', fr: 'étudier', de: 'studieren' },
  aprender: { en: 'learn', es: 'aprender', fr: 'apprendre', de: 'lernen' },
  ensinar: { en: 'teach', es: 'enseñar', fr: 'enseigner', de: 'lehren' },
  ler: { en: 'read', es: 'leer', fr: 'lire', de: 'lesen' },
  escrever: { en: 'write', es: 'escribir', fr: 'écrire', de: 'schreiben' },
  cozinhar: { en: 'cook', es: 'cocinar', fr: 'cuisiner', de: 'kochen' },
  lavar: { en: 'wash', es: 'lavar', fr: 'laver', de: 'waschen' },
  limpar: { en: 'clean', es: 'limpiar', fr: 'nettoyer', de: 'putzen' },
  // Tecnologia
  usar: { en: 'use', es: 'usar', fr: 'utiliser', de: 'benutzen' },
  configurar: { en: 'configure', es: 'configurar', fr: 'configurer', de: 'konfigurieren' },
  atualizar: { en: 'update', es: 'actualizar', fr: 'mettre à jour', de: 'aktualisieren' },
  baixar: { en: 'download', es: 'descargar', fr: 'télécharger', de: 'herunterladen' },
  enviar: { en: 'send', es: 'enviar', fr: 'envoyer', de: 'senden' },
  receber: { en: 'receive', es: 'recibir', fr: 'recevoir', de: 'empfangen' },
  salvar: { en: 'save', es: 'guardar', fr: 'sauvegarder', de: 'speichern' },
  apagar: { en: 'delete', es: 'borrar', fr: 'supprimer', de: 'löschen' },
  editar: { en: 'edit', es: 'editar', fr: 'modifier', de: 'bearbeiten' },
  copiar: { en: 'copy', es: 'copiar', fr: 'copier', de: 'kopieren' },
  // Natureza
  brilhar: { en: 'shine', es: 'brillar', fr: 'briller', de: 'scheinen' },
  queimar: { en: 'burn', es: 'quemar', fr: 'brûler', de: 'brennen' },
  congelar: { en: 'freeze', es: 'congelar', fr: 'geler', de: 'frieren' },
  crescer: { en: 'grow', es: 'crecer', fr: 'croître', de: 'wachsen' },
  // Corpo
  bater: { en: 'hit', es: 'golpear', fr: 'frapper', de: 'schlagen' },
  segurar: { en: 'hold', es: 'sostener', fr: 'tenir', de: 'halten' },
  abrir: { en: 'open', es: 'abrir', fr: 'ouvrir', de: 'öffnen' },
  fechar: { en: 'close', es: 'cerrar', fr: 'fermer', de: 'schließen' },
  apertar: { en: 'squeeze', es: 'apretar', fr: 'serrer', de: 'drücken' },
  soltar: { en: 'release', es: 'soltar', fr: 'lâcher', de: 'loslassen' },
  cortar: { en: 'cut', es: 'cortar', fr: 'couper', de: 'schneiden' },
  amarrar: { en: 'tie', es: 'atar', fr: 'attacher', de: 'binden' },
  // Cálculos
  calcular: { en: 'calculate', es: 'calcular', fr: 'calculer', de: 'berechnen' },
  comparar: { en: 'compare', es: 'comparar', fr: 'comparer', de: 'vergleichen' },
  avaliar: { en: 'evaluate', es: 'evaluar', fr: 'évaluer', de: 'bewerten' },
  testar: { en: 'test', es: 'probar', fr: 'tester', de: 'testen' },
  tentar: { en: 'try', es: 'intentar', fr: 'essayer', de: 'versuchen' },
  // Emoções
  amar: { en: 'love', es: 'amar', fr: 'aimer', de: 'lieben' },
  gostar: { en: 'like', es: 'gustar', fr: 'aimer', de: 'mögen' },
  preferir: { en: 'prefer', es: 'preferir', fr: 'préférer', de: 'bevorzugen' },
  querer: { en: 'want', es: 'querer', fr: 'vouloir', de: 'wollen' },
  precisar: { en: 'need', es: 'necesitar', fr: 'avoir besoin de', de: 'brauchen' },
  conseguir: { en: 'achieve', es: 'conseguir', fr: 'réussir', de: 'schaffen' },
  // Social
  ajudar: { en: 'help', es: 'ayudar', fr: 'aider', de: 'helfen' },
  agradecer: { en: 'thank', es: 'agradecer', fr: 'remercier', de: 'bedanken' },
  pedir: { en: 'ask for', es: 'pedir', fr: 'demander', de: 'bitten' },
  aceitar: { en: 'accept', es: 'aceptar', fr: 'accepter', de: 'akzeptieren' },
  compartilhar: { en: 'share', es: 'compartir', fr: 'partager', de: 'teilen' },
  // Cozinha
  assar: { en: 'bake', es: 'hornear', fr: 'cuire au four', de: 'backen' },
  fritar: { en: 'fry', es: 'freír', fr: 'frire', de: 'braten' },
  misturar: { en: 'mix', es: 'mezclar', fr: 'mélanger', de: 'mischen' },
  servir: { en: 'serve', es: 'servir', fr: 'servir', de: 'servieren' },
  // Transporte
  dirigir: { en: 'drive', es: 'conducir', fr: 'conduire', de: 'fahren' },
  viajar: { en: 'travel', es: 'viajar', fr: 'voyager', de: 'reisen' },
  visitar: { en: 'visit', es: 'visitar', fr: 'visiter', de: 'besuchen' },
  chegar: { en: 'arrive', es: 'llegar', fr: 'arriver', de: 'ankommen' },
  // Construção
  construir: { en: 'build', es: 'construir', fr: 'construire', de: 'bauen' },
  quebrar: { en: 'break', es: 'romper', fr: 'casser', de: 'brechen' },
  reparar: { en: 'repair', es: 'reparar', fr: 'réparer', de: 'reparieren' },
  // Dinheiro
  comprar: { en: 'buy', es: 'comprar', fr: 'acheter', de: 'kaufen' },
  vender: { en: 'sell', es: 'vender', fr: 'vendre', de: 'verkaufen' },
  pagar: { en: 'pay', es: 'pagar', fr: 'payer', de: 'bezahlen' },
  investir: { en: 'invest', es: 'invertir', fr: 'investir', de: 'investieren' },
  gastar: { en: 'spend', es: 'gastar', fr: 'dépenser', de: 'ausgeben' },
  // Auxiliares
  ser: { en: 'be', es: 'ser', fr: 'être', de: 'sein' },
  estar: { en: 'be', es: 'estar', fr: 'être', de: 'sein' },
  ter: { en: 'have', es: 'tener', fr: 'avoir', de: 'haben' },
  fazer: { en: 'do', es: 'hacer', fr: 'faire', de: 'machen' },
  ir: { en: 'go', es: 'ir', fr: 'aller', de: 'gehen' },
  vir: { en: 'come', es: 'venir', fr: 'venir', de: 'kommen' },
  dar: { en: 'give', es: 'dar', fr: 'donner', de: 'geben' },
  tomar: { en: 'take', es: 'tomar', fr: 'prendre', de: 'nehmen' },
  trazer: { en: 'bring', es: 'traer', fr: 'apporter', de: 'bringen' },
  parecer: { en: 'seem', es: 'parecer', fr: 'sembler', de: 'scheinen' },
  existir: { en: 'exist', es: 'existir', fr: 'exister', de: 'existieren' },
  funcionar: { en: 'work', es: 'funcionar', fr: 'fonctionner', de: 'funktionieren' },
  mudar: { en: 'change', es: 'cambiar', fr: 'changer', de: 'ändern' },
  mostrar: { en: 'show', es: 'mostrar', fr: 'montrer', de: 'zeigen' },
  passar: { en: 'pass', es: 'pasar', fr: 'passer', de: 'vorbeigehen' },
};
